### ISSUE TITLE
Why do unexpected method calls cause test failure ?

### ISSUE THREAD

**Issue by mariusstaicu** [golang/mock#105]
As a user of mocks, I would like to have the possibility to choose which calls I really need to verify.
Therefore, unexpected method calls should issue only a warning in the test fail, in should not cause the test to fail.
ie, in controller.go, instead of:
```go
expected, err := ctrl.expectedCalls.FindMatch(receiver, method, args)
if err != nil {
	origin := callerInfo(2)
	ctrl.t.Fatalf("Unexpected call to %T.%v(%v) at %s because: %s", receiver, method, args, origin, err)
}
```

should be

```go
expected, err := ctrl.expectedCalls.FindMatch(receiver, method, args)
if err != nil {
	origin := callerInfo(2)
	ctrl.t.Logf("Unexpected call to %T.%v(%v) at %s because: %s", receiver, method, args, origin, err)
}
```

**Comment by balshetzer** [comment]
This issue is similar to #7. It's a reasonable request. I'll look into it. Meanwhile, I will close this issue and track it on #7.
