### ISSUE TITLE
Mocks cannot safely be passed to other goroutines

### ISSUE THREAD

**Issue by jimpo** [golang/mock#110]
If a mock expectation fails, it attempts to fail the test using testing.T.Fatalf (see [here](https://github.com/golang/mock/blob/45f67fc6bd1ec393ae6c0145e35d67b3867bbe96/gomock/controller.go#L132)). Fatalf in turn exits the current goroutine with `runtime.Goexit()`. However, if the mock is being using in a goroutine other than the testing thread, it will not exit the testing thread. Even worse, it can cause the current goroutine to exit in an unexpected way which in my application skips cleanup and causes a deadlock in the test. While I could refactor a bunch of stuff to do cleanup with defers, I see no benefit other than accommodating this behavior of gomock at the expense of additional complexity. Are there any known solutions?

**Comment by balshetzer** [comment]
gomock calls Fatalf on the [TestReporter](https://github.com/golang/mock/blob/master/gomock/controller.go#L67) that you pass to the Controller's constructor. That doesn't have to be a testing.T. You can create your own TestReporter that does whatever you want when Fatalf is called.

**Comment by balshetzer** [comment]
Please let me know if these suggestions resolved your issue or not. If yes, let's close this. If not then please explain so we can try to resolve it.

**Comment by jimpo** [comment]
https://github.com/golang/mock/pull/111 provides an acceptable workaround for me, so I'll close.
