### ISSUE TITLE
Build Failing - Missing "context" package

### ISSUE THREAD

**Issue by aludvik** [golang/mock#116]
After #111  was merged, I am now getting build failures in our CI process with the error:

`cannot find package "context" in any of:`

and then a list of directories in GOPATH.

**Comment by aludvik** [comment]
Running `go get -u github.com/golang/mock/gomock` also fails with `package context: unrecognized import path "context" (import path does not begin with hostname)`

**Comment by balshetzer** [comment]
Which version of Go are you using?

**Comment by aludvik** [comment]
We are using the golang-1.6 package in the Ubuntu 16.04 release:
```
root@be91d814ef5c:/# apt-cache show golang-1.6
Package: golang-1.6
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 78
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 1.6.2-0ubuntu5~16.04.3
Depends: golang-1.6-doc (>= 1.6.2-0ubuntu5~16.04.3), golang-1.6-go (>= 1.6.2-0ubuntu5~16.04.3), golang-1.6-src (>= 1.6.2-0ubuntu5~16.04.3)
Description: Go programming language compiler - metapackage
 The Go programming language is an open source project to make
 programmers more productive. Go is expressive, concise, clean, and
 efficient. Its concurrency mechanisms make it easy to write programs
 that get the most out of multicore and networked machines, while its
 novel type system enables flexible and modular program construction.
 Go compiles quickly to machine code yet has the convenience of
 garbage collection and the power of run-time reflection. It's a
 fast, statically typed, compiled language that feels like a
 dynamically typed, interpreted language.
 .
 This package is a metapackage that, when installed, guarantees
 that (most of) a full Go development environment is installed.
Description-md5: 8650a23f44e2d60a785ad3123733d6d8
Homepage: https://golang.org
Original-Maintainer: Go Compiler Team <pkg-golang-devel@lists.alioth.debian.org>
```

**Comment by aludvik** [comment]
https://github.com/hyperledger/sawtooth-core/blob/master/docker/sawtooth-dev-go

**Comment by balshetzer** [comment]
That explains why this is happening. The context package was only added in Go 1.7.

If at all possible, I think you should upgrade your image to use [Go 1.9.1 (that's the latest release)](https://golang.org/doc/devel/release.html#go1.9.minor). This _should_ be simple since the Go releases are backwards compatible since 1.0. 

If that's not possible then you can pin gomock to the latest version that worked for you. That would be 4887ba10eac80f57bfb3de234db4ac970d786511.

I don't think we should try to fix this in the gomock package.

**Comment by balshetzer** [comment]
Despite what I said before, backwards compatibility was restored in #118
