### ISSUE TITLE
Explicitly block in returned channel?

### ISSUE THREAD

**Issue by RONNCC** [golang/mock#117]
Is there anyway to specify behavior for sockets/channels/mocks of network primitives to block after exhausting the values in `Return()` 

(Is it accurate to say the current alternative seems to be to emulate a `IO.EOF` , rather than block?) 

This would allow better testing for select statements in particular.

------

Similarly is there a suggested way to return a list of items using `.RETURN.`? e.g. 1,2,3 on a channel rather than just the same item consistently?

**Comment by balshetzer** [comment]
Can you give me examples of what you're trying to do? Then I can try to demonstrate a solution.

**Comment by balshetzer** [comment]
I'm going to close this issue for now. Feel free to re-open with more info.

**Comment by RONNCC** [comment]
Sorry this is a number of things - I'm trying to meet the following cases:

1) Mock an API - you want the API to return $x, $y, and then error or block (i.e. it has nothing left)
2) Mock a channel - if you're testing `sum` you want something like `sum { elements <- channel }`where `channel = Channel(1,2,3,4 ... )` to test you are correctly summing the elements in a channel and then hitting a default timer case
