### ISSUE TITLE
Travis CI builds do not test golang < 1.7

### ISSUE THREAD

**Issue by jeking3** [golang/mock#119]
Did the project drop support for golang < 1.7?  Ubuntu Xenial comes with go 1.6.2.

**Comment by balshetzer** [comment]
Hi James,

The Go team only supports the last two major versions of Go. Right now that is 1.9 and 1.8. All the versions of Go after 1.0 are backwards compatible so it seems odd to me that people would want to stay with an older version. Additionally, it will be difficult for gomock to keep supporting all older versions.

Can you please help me understand why someone would prefer to use an older version of Go? Is it just that Ubuntu Xenial comes with 1.6.2? Is it hard for you to install a newer version?

Thanks,
Hesky

**Comment by jeking3** [comment]
Correct, Ubuntu Xenial comes with 1.6.2 and that is our current reference image for running go tests.  Traditionally the Apache Thrift project has had (too) long standing support for older versions of software.  Given you are telling me that golang before 1.8 isn't supported any more, I see little reason to support older versions in Apache Thrift.  I will bring this up with the rest of the development team and resolve this if appropriate.

**Comment by balshetzer** [comment]
I'm happy to add 1.6 to the CI if you want to send a PR. At the very least, it'll tell us if we break compatibility again and we can decide then if that's OK.

**Comment by balshetzer** [comment]
We've added 1.6 tests back to the CI but it's going to fail because we use t.Run in the tests and that was added in Go 1.7.

**Comment by jeking3** [comment]
Well, in the end projects have to update.  Fortunately, having the backwards compatible context used here is going to ease transition issues for a great many dependent projects, so thanks for adding that.
