### ISSUE TITLE
support for singleton mock service

### ISSUE THREAD

**Issue by tnclong** [golang/mock#122]
I had a api mount to http depend on ServiceA. So I mock ServiceA called `MockServiceA`.
I run the api use `TestMain(m *testing.M)` at `:9000` and need new a MockServiceA.
But I don't have a `TestReporter`.
Also
I have 
`TestAxx(t *tesing.T)`
`TestABxx(t *testing.T)`

I want `TestAxx` and `TestABxx` use a same `MockServiceA`.

Do you have any idea about this case?

Thanks for your any input.

**Comment by balshetzer** [comment]
You can write a TestReporter implementation that just panics on any error and use it to create your mock outside of the test function. You can also make your TestReporter implementation redirect to the t if you assign it inside your test. Then you can set it inside your test to make it behave like a regular TestReporter. For example:

type myTestReporter struct{
  t TestReporter
}

func (m *myTestReporter) Errorf(format string, args ...interface{}) {
  if m.t == nil {
    panic(fmt.Sprintf(format, args...))
  }
  m.t.Errorf(format, args...)
}

func (m *myTestReporter) Fatalf(format string, args ...interface{}) {
if m.t == nil {
    panic(fmt.Sprintf(format, args...))
  }
  m.t.Fatalf(format, args...)
}

Use the above to make your controller and mock. Then inside your TestAxx function:
myController.t = t
Then make sure to set it to nil by the end of the test like:
defer func() { myController.t = nil }

**Comment by tnclong** [comment]
Thank you very much. I wrote a TestReporter like your code yestoday and all my test cases work well.
 Only one question for me now. Would that be a official support TestReporter? I think singleton service used by multi test cases is normal on web api develop. Feel free to reject me. I also think write my own TestReporter is easy.

**Comment by poy** [comment]
@tnclong It looks like `TestMain` deliberately does not allow for assertions. I don't know that we want to include something that goes against this.
