### ISSUE TITLE
Make source mode command line arguments consistent with reflect mode

### ISSUE THREAD

**Issue by sam701** [golang/mock#136]
Here is the basic usage of the reflect mode 
```
mockgen database/sql/driver Conn,Driver
```
It would be helpful to make the source mode usage to be like this:
```
mockgen -source-dir myPackageDir privateInterface1,privateInterface2,PublicInterface3
```

This approach has a few benefits:
1. All generated mocks of a package will reside in a single file. Currently if you need to mock just a couple of interfaces, you might run `mockgen` for every single file in the package. This leads to many unneeded files. Some of them don't contain any mocks. Additionally you cannot do it in a single `mockgen` call but have to loop in a script file.
1. It makes straightforward to mock specific private interfaces. Currently all interfaces from the source file will be mocked, even if some of them are not required to be mocked.
1. Last but not least, it is consistent with the reflect mode.

**Comment by codyoss** [comment]
This has not gained much traction and I would like to avoid changing how the modes work at this point. In the future the hope is that the modes will converge.
