### ISSUE TITLE
Documentation references inexistent script: update_mocks.sh

### ISSUE THREAD

**Issue by mapleoin** [golang/mock#142]
The README at: https://github.com/golang/mock/blob/master/sample/README.md mentions an inexistent script used to generate the sample code:

> See ../update_mocks.sh for the command used to generate it.

**Comment by dmitris** [comment]
the script `update_mocks.sh` disappeared with this commit: https://github.com/golang/mock/commit/2f854191f024ae2f877a77cfac9f0c04a00a9ddc and was replaced by `go:generate` statements.  Currently the `go:generate` is in https://github.com/golang/mock/blob/master/gomock/matchers.go#L1  

Sent PR #205 to remove the reference
