### ISSUE TITLE
Include mockgen binaries with tagged releases

### ISSUE THREAD

**Issue by tyler-luminal** [golang/mock#147]
It would be really helpful to include `mockgen` binaries with tagged releases similar to [glide](https://github.com/Masterminds/glide/releases). This makes it easier for using the correct version of `mockgen` to generate mocks for a specific version of `gomock`.

**Comment by sugarjig** [comment]
If I'm not mistaken, this is the same as #95.

**Comment by scevallos** [comment]
Opened #229 addressing this issue
