### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by cyberhck** [golang/mock#161]
Do we have timeline of when's new version gonna ged released? there's only one release which doesn't work for me

**Comment by balshetzer** [comment]
Can you be more specific about what you need?

**Comment by cyberhck** [comment]
I use dep for managing dependencies, and it pulls 1.0.0 version by default which is broken for me, I need master for now, so asking for a new release :)

**Comment by ngauthier** [comment]
@cyberhck use a constraint to set the revision you want:

https://golang.github.io/dep/docs/Gopkg.toml.html#constraint

**Comment by cyberhck** [comment]
I'm already using constraint and it's set to master, however what I want is golang/mock to release maybe 1.1.0 or any new version so I don't reference from master.

**Comment by balshetzer** [comment]
There is now a v1.0.1. I hope that helps.
