### ISSUE TITLE
flags for reflect

### ISSUE THREAD

**Issue by jmhodges** [golang/mock#18]
Would it be okay if I put up a PR to add the ability to use flags from the source generation to the reflect case? More accurately, adding some kind of `-reflectOver` and `-interfaces` flags.

This would let folks override the package name the reflect generation makes without having to do sed work.

For instance, we have linting tools that complain about underscores in package names but the interfaces I need are in another package and it would be convenient to refer to those interfaces by package and not source file. I've already got a really long sed in our `go:generate` to correct the import prefix of `gomock` in the generated file and another one would be unfortunate.

**Comment by dsymonds** [comment]
The general solution is: don't run lint over generated code. Generated code does all kinds of things to avoid naming conflicts and other issues that don't arise for human-written code.

I'm not clear on what `-reflectOver` or `-interfaces` would do, though. Can you describe that in more detail? e.g. the `-package` flag already controls what the generated package name is, so your second paragraph should already be moot.

**Comment by jmhodges** [comment]
I see what I did. The `-package` flag has to come before, not after, the free standing ones. Okay. 

I'll make maybe another README diff calling that out. Thanks again.
