### ISSUE TITLE
Allow setting of ctrl object after instantiation

### ISSUE THREAD

**Issue by yfronto** [golang/mock#183]
When testing code that uses a postgres DB, I mock out the interfaces in database/sql/driver.

# The Problem

* The `gomock.NewController` function requires a reference to a `testing.T` object, which is unique to a test case and can't be updated after instantiation.
* The `<mock_package>.NewMock<interface>` function requires a reference to a `gomock.Controller`, which can't be updated after instantiation (thus binding the mock object to the test case).
* The `sql.Register` function takes a reference to a driver, which I've mocked and can only be called once.

# Workaround

* In the same package where one puts mocked interfaces, add a mock accessor file that allows override of the `gomock.Controller` for each mocked object. For each test case, create a new `gomock.Controller` and update each mocked object with it.

Sample: https://github.com/yfronto/sqlmock

# Solution

One of two options:

1. Allow setting of the `testing.T` object on an existing `gomock.Controller`
1. Allow setting of the `gomock.Controller` object on an existing mocked object

Please let me know if I'm just being silly and there's a more straightforward way to accomplish mocking interfaces for packages that follow the driver model. I'm happy to supply the PR for this, if you like.

**Comment by balshetzer** [comment]
The controller actually takes a TestReporter. testing.T implements TestReporter. You can have your own TestReporter that forwards to a testing.T that you can change.

Something like this: https://github.com/golang/mock/issues/122#issuecomment-338743825

**Comment by yfronto** [comment]
Figures I was missing something fairly obvious. I didn't even notice it was a TestReporter.

Thanks for the response!
