### ISSUE TITLE
 got panic from mock data

### ISSUE THREAD

**Issue by wotmshuaisi** [golang/mock#185]
Running tool: /usr/lib/golang/bin/go test -timeout 30s xxx/micro-service-user/service -run ^Test_userinfoService_Register$

panic: test executed panic(nil) or runtime.Goexit

goroutine 7 [running]:
testing.tRunner.func1(0xc4200ae1e0)
	/usr/lib/golang/src/testing/testing.go:711 +0x2d2
runtime.Goexit()
	/usr/lib/golang/src/runtime/panic.go:366 +0x147
testing.(*common).FailNow(0xc4200ae0f0)
	/usr/lib/golang/src/testing/testing.go:544 +0x39
testing.(*common).Fatalf(0xc4200ae0f0, 0x54e4be, 0x2e, 0xc420082190, 0x5, 0x5)
	/usr/lib/golang/src/testing/testing.go:588 +0x83
github.com/golang/mock/gomock.(*Controller).Call.func1(0xc42000e3f0, 0x52b3a0, 0xc420052490, 0x547a9c, 0xb, 0xc420052530, 0x1, 0x1, 0x0, 0x0, ...)
	/home/xxx/go/src/github.com/golang/mock/gomock/controller.go:150 +0x4d4
github.com/golang/mock/gomock.(*Controller).Call(0xc42000e3f0, 0x52b3a0, 0xc420052490, 0x547a9c, 0xb, 0xc420052530, 0x1, 0x1, 0x410201, 0x80, ...)
	/home/xxx/go/src/github.com/golang/mock/gomock/controller.go:166 +0xdc
xxx/micro-service-user/models.(*MockUserinfoModel).UserinfoGet(0xc420052490, 0x547b36, 0xb, 0x4b5fce)
	/home/xxx/go/src/xxx/micro-service-user/models/mockinterface.go:73 +0xe8
xxx/micro-service-user/service.(*userinfoService).Register(0xc420077f48, 0x547b36, 0xb, 0x546c85, 0x6, 0x546f3e, 0x7, 0x5c6e00, 0xf, 0x5e01c7)
	/home/xxx/go/src/xxx/micro-service-user/service/service.go:24 +0x97
xxx/micro-service-user/service.Test_userinfoService_Register.func1(0xc4200ae1e0)
	/home/xxx/go/src/xxx/micro-service-user/service/service_test.go:85 +0xa0
testing.tRunner(0xc4200ae1e0, 0xc420052500)
	/usr/lib/golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:789 +0x2de
FAIL	xxx/micro-service-user/service	0.004s
Error: Tests failed.

**Comment by wotmshuaisi** [comment]
code: https://github.com/wotmshuaisi/micro-service-user/blob/master/service/service_test.go

**Comment by balshetzer** [comment]
The problem is that the mock and controller are created outside the Run so it gets the testing.T from the top function instead of the testing.T from the Run function.

The testing package gets confused when t.Fatal gets called by the mock on the wrong testing.T so it just reports that someone panicked, not knowing that it was the other testing.T that did it.

See here for a clearer explanation: https://github.com/golang/mock/issues/51#issuecomment-324423178
