### ISSUE TITLE
Tests do not fail when EXPECT() is called on a mock

### ISSUE THREAD

**Issue by estutzenberger** [golang/mock#194]
Perhaps I have a misunderstanding about `EXPECT()`. I have a test in which I am trying to validate that it can in fact fail.  I added some `EXPECT()` calls that I know will not be called. I expect that when I call `EXPECT()` on a mock interface and that method is never called, the test will fail. However, that does not seem to be the case.

Is this expected behavior?

Example:
``` go
func SomeTest(t *testing.T) {
    ctrl := gomock.NewController(t)

    client := mock.NewMockClient(ctrl)
    
    client.EXPECT().SomeFunc().Return(5).MinTimes(1)
    client.EXPECT().SomeOtherFunc().Return(nil)

    //this function does not call either of the above, but this test passes
    FunctionUnderTest()
}
```

**Comment by balshetzer** [comment]
The last part is to call `client.Finish()`. This asserts that all expectations have been met. The common pattern is to call `defer client.Finish()` right after creating the mock.

**Comment by estutzenberger** [comment]
Ahh, OK. Thanks!

**Comment by estutzenberger** [comment]
FWIW, it should be `ctrl.Finish()` rather than `client.Finish()`.

**Comment by balshetzer** [comment]
Oops, thanks for the correction.

**Comment by omar-scio** [comment]
@balshetzer Seeing this issue on go@1.17.3

We do not have any `defer mockCtrl.Finish` statements since [the docs](https://pkg.go.dev/github.com/golang/mock/gomock#Controller) say we don't need to. Even with that line, the test still erroneously passes (even though an expected call was never actually made).

Any ideas?
