### ISSUE TITLE
add some examples to the tests?

### ISSUE THREAD

**Issue by turtleDev** [golang/mock#198]
Hello Gophers,

When I came across this package, I had issue wrapping my brain around what it does. When this happens, I'll usually look at examples since they solidify any assumptions. However there aren't any available for this package.

It would be nice if we could have some examples in here. :)

Alternatively, I'd be happy to contribute some.
Cheers!

**Comment by poy** [comment]
Does 03ad011df2d8a4e27639aa9a4f7f88b5fe87a812 help at all? Also there is a samples package that might help.

**Comment by codyoss** [comment]
Closing for now as some examples were added. If we need more please feel free to reopen with a more specific use-case. Thanks for the report!
