### ISSUE TITLE
Order of specifying MinTime and MaxTime matters for some cases

### ISSUE THREAD

**Issue by timoha** [golang/mock#204]
If I'd like to set expectation that a method gets called 1 or 42 times, specifying `MinTime(1).MaxTime(42)` ends up to be an expectation of 0 to 42 times (because `MaxTime` sets `minCalls = 0` if `minCalls == 1`: https://github.com/golang/mock/blob/master/gomock/call.go#L101)). However, if I specify `MaxTime(42).MinTime(1)`, it behaves as expected.

**Comment by codyoss** [comment]
Hey @timoha thanks for the report. Can you confirm that this is still an issue?

**Comment by codyoss** [comment]
This has been documented more clearly now. Closing. Feel free to reopen if the docs don't cover this adequately. Thanks for the report!
