### ISSUE TITLE
Add a way to retrieve a mocked method with a string

### ISSUE THREAD

**Issue by mbyio** [golang/mock#206]
I want to write some tests where I make sure the function properly handles errors from any of the methods on a mock. There are a couple of ways to do this, but no real obvious way (please correct me if I'm wrong). My basic idea is to iterate over the methods on the mock that I want to error out and generate a new test for each of them where all the other methods succeed but that one targeted method fails. This isn't too difficult, but it requires me to write some custom mapping code that maps a string to a method name.

What I'd really like instead is a way to get a `*gomock.Call` for any arbitrary mocked method using its name as a string. Something like `mock.EXPECT().METHOD("MyMockedMethod")`.

**Comment by codyoss** [comment]
@mbyio would you mind providing a more detailed code snippet? I am not sure if this is something I would want to add, but I am willing to see a more detailed example of what you are talking about first.

**Comment by mbyio** [comment]
TBH this was so long ago, I'm not sure I can give a good example anymore. I'll close this and reopen if it comes up again.
