### ISSUE TITLE
What about the inline function？

### ISSUE THREAD

**Issue by houxl123** [golang/mock#209]
when mock,the function is very small, like
`
	func newClinet() Clinet{
		return &clien
	}
`
The mock fails because this function is inline.What should I do?

**Comment by balshetzer** [comment]
I don't understand the question. Please explain what you are trying to do, what happens, and what you would have liked to happen. Please provide as much detail as possible and then reopen the issue.

**Comment by houxl123** [comment]
@balshetzer I am very sorry, I am not clear about the problem description. Look at the code below. When `fmt.Println("max")` is masked, the mock fails. When `fmt.Println("max")` is turned on, the mock succeeds.This is because max is an inline function, so how to deal with this problem?
`
func max (m,n int) int {
	//fmt.Println("max")
	if m > n {
		return m
	}
	return n
}

func min (m,n int) int {
	if m < n {
		return m
	}
	return n
}
func TestMock(t *testing.T){
	monkey.Patch(max,min)
	if max(0,1) == 0 {
		t.Log("mock success")
	} else {
		t.Error("mock fail")
	}
}
`
