### ISSUE TITLE
False positives: EXPECT() doesn't fail when mocked function not called

### ISSUE THREAD

**Issue by ameyer-pivotal** [golang/mock#213]
Writing a test that includes `someMock.EXPECT().SomeMethod("foo")` will only fail if `SomeMethod()` is called at least once, and perhaps with the wrong arguments (`"bar"` vs `"foo"`). The EXPECT will not fail if `SomeMethod()` is never called at all, even when appending `.Times(1)` or `.MinTimes(1)` to it.

This leads to falsely passing tests when the call to `SomeMethod()` is accidentally omitted in production code.

**Comment by poy** [comment]
Are you calling [Controller.Finish](https://godoc.org/github.com/golang/mock/gomock#Controller.Finish)?

Finish() will fail the test if the methods were not invoked.

**Comment by ameyer-pivotal** [comment]
I was not. Good to know, and I'll keep that in mind. Thanks!
