### ISSUE TITLE
STUBS method

### ISSUE THREAD

**Issue by duskhacker** [golang/mock#24]
Ok, now that we've got the *Times thing out of the way, the other thing I really miss is a STUBS method. I'd like to discuss this first with you before I go and try to contribute it, maybe cut down on the back-and-forth a bit. 

When I've used other mocking frameworks, I use 

* A "STUBS" method to indicate "This test does not care that this method is called, it is simply here to allow the code under test to run"
* A "EXPECTS" method to indicate "This is the expectation that this test cares about" 

Would you be open to that addition?

**Comment by dsymonds** [comment]
STUBS is just EXPECT + AnyTimes, is it not?

**Comment by duskhacker** [comment]
It's more like EXPECTS.Call(gomock.Any()).Anytimes()

**Comment by duskhacker** [comment]
In fact, the above is pretty much what I'm using now, but IMHO, STUBS would make tests clearer.

**Comment by dsymonds** [comment]
Yeah, that's what I meant. So it'd be just syntactic sugar for that?

**Comment by duskhacker** [comment]
Yes, no arg checking, no checking of number of calls.

**Comment by duskhacker** [comment]
And to be clear, yes, it's syntactic sugar.

**Comment by dsymonds** [comment]
My initial instinct is to say no. I don't want to complicate the API for something that is relatively simple to do already. People have been using gomock to produce stubs for years without issue.

But I'll have a think about it.

**Comment by duskhacker** [comment]
Ok, I respect that. I just want to add that I think it would make scanning through tests easier and clearer if STUBS was available, and people coming from other mocking frameworks might miss it like I do. I'll of course defer to your decision when you've thought through it.

**Comment by dsymonds** [comment]
I think I'd prefer to leave things as they are. Thanks anyway.
