### ISSUE TITLE
proposal: change order expectations are evaluated

### ISSUE THREAD

**Issue by poy** [golang/mock#246]
Add option to `NewController()` (see #238 ) to enable reversing the evaluation order.

### Proposal

[gmock](https://github.com/abseil/googletest/tree/master/googlemock) applies expectations in reverse order. This allows the following pattern:

```go
// sut.go
type A interface {
  Foo(i int) int
}

type Something struct{
  a A
}

func NewSomething(a A) *Something {
  return Something{}
}

func (s *Something) Do(i int) {
  s.a.Foo(i)
}

// sut_test.go
func beforeEach(t *testing.T) A {
  ctrl := gomock.NewController(t)
  mockA := NewMockA()

  // Stub - Always returns 99
  mockA.
    EXPECT().
    Foo(gomock.Any()).
    Return(99).
    AnyTimes()
}

func TestFoo_OnlyDefault(t *testing.T){
  mockA := beforeEach(t)
  
  s := NewSUT(mockA)
  s.Do(5) // Mock doesn't make any assertion on value
}

func TestFoo_WithAssertion(t *testing.T){
  mockA := beforeEach(t)
  
  mockA.
    EXPECT().
    Foo(101).
    Return(99)

  s := NewSUT(mockA)
  s.Do(5) // Latest assertion will fail
}
```

This pattern will currently fail as the first assertion is evaluated first, as it is an `AnyTimes()`, it will always be successful and therefore the last assertion (the one we really care about for `TestFoo_WithAssertion`) won't be applied.

**Comment by poy** [comment]
Related to #137 #188 #7

**Comment by tocrafty** [comment]
Agreed. This would be very usefull to inject faults to mocked objects.

**Comment by codyoss** [comment]
Closing issue as I believe this is captured by #238
