### ISSUE TITLE
Doesn't import source file's package if mocked interface uses models defined in the same package.

### ISSUE THREAD

**Issue by anasanzari** [golang/mock#249]
Consider the case:
```go
type Dao interface {
  Get() (model Model)
}

// model.go same package
type Model struct {...}
```

command used: `mockgen --destination=./mocks/mock_dao.go --source=./dao/dao.go Dao`

**Comment by poy** [comment]
@anasanzari I created a test that emulates what you have described. However it appears to work correctly. I reinstalled mockgen at SHA 5f3a40bc29aa3f8115e37b1ae65fe38747f39816.

Recreate script:
```bash
mkdir $GOPATH/src/github.com/golang/mock/mockgen/internal/tests/diff_package
pushd !$
cat << EOF >> dao.go
package diffpackage

//go:generate mockgen --destination=./mocks/mock_dao.go --source=dao.go Dao

type Dao interface {
	Get() (model Model)
}

type Model struct{}
EOF

go generate ./...
go test ./...
popd
```

For me, when I looked at `mocks/mock_dao.go`, I saw `Model` used as `diff_package.Model` and the import for `github.com/golang/mock/mockgen/internal/tests/diff_package` was named `diff_package`.

**Comment by anasanzari** [comment]
Yes, it worked after updating. Thank!
