### ISSUE TITLE
Mock External Dependency not Directly Embedded

### ISSUE THREAD

**Issue by jon-whit** [golang/mock#260]
I'd like to use the mock package to mock the behavior of the [`Conn`](https://godoc.org/github.com/gomodule/redigo/redis#Conn) interface defined in the [github.com/gomodule/redigo/redis](https://godoc.org/github.com/gomodule/redigo/redis) package. I'm quite new to the mock package and am having difficulty understanding what I need to do to mock this external dependency. Here's a snippet of the Go code I'm dealing with:

```
type DataAccessLayer struct {
	RedisPool *redis.Pool
}

func (dal *DataAccessLayer) ListPosts() ([]*Post, error) {
    conn := dal.RedisPool.Get()
    defer conn.Close()

    resp, err := conn.Do("GET", "posts") // Want to mock this
    if err != nil {
        return nil, err
    }

    return deserialize(resp), nil
}
```

The [`redis.Pool`](
https://godoc.org/github.com/gomodule/redigo/redis#Pool) type implements the `Conn` interface, but the interface isn't embedded in the `DataAccessLayer` structure directly.

I'd like to be able to mock the `Do(commandName string, args ...interface{}) (reply interface{}, err error)` method of the `Conn` interface.

Something like:
```
mockObj.
    EXPECT().
    Do("GET", []interface{}{"posts"}).
    Return(nil, errors.New("Redis error"))
```

Could someone point me in the right direction and give me some guidance? Any help would be much appreciated!

**Comment by poy** [comment]
So you will need to create an interface for `*redis.Pool`. That way when you do ` conn := dal.RedisPool.Get()`, you can actually interact with a mock and it can return a mock.

**Comment by jon-whit** [comment]
@poy Something like this then?

```
mockCtrl := gomock.NewController(t)
defer mockCtrl.Finish()

mockPool := mocks.NewMockRedisPool(mockCtrl)
mockConn := mocks.NewMockRedisConn(mockCtrl)

mockPool.EXPECT().Get().Return(mockConn).Times(1)
mockConn.EXPECT().Do("GET", "foo").Return("bar", nil).Times(1)
```

**Comment by poy** [comment]
I've not tried it, but that looks right.

**Comment by jon-whit** [comment]
In `interfaces/redis.go` I have:
```
type RedisPool interface {
	ActiveCount() int
	Close() error
	Get() redis.Conn
	GetContext(ctx context.Context) (redis.Conn, error)
	IdleCount() int
	Stats() redis.PoolStats
}
```
which defines an interface for [redis.Pool](https://godoc.org/github.com/gomodule/redigo/redis#Pool).

I replace the *redis.Pool with this interface.
```
type DataAccessLayer struct {
	RedisPool interfaces.RedisPool
}
```

And write a test like this:
```
func TestReadPolicy(t *testing.T) {
	mockCtrl := gomock.NewController(t)
	defer mockCtrl.Finish()

	mockPool := mocks.NewMockRedisPool(mockCtrl)
	mockConn := mocks.NewMockConn(mockCtrl)

	dal := &DataAccessLayer{
		RedisPool: mockPool,
	}

	posts, err := dal.ListPosts()

	gomock.InOrder(
		mockPool.EXPECT().Get().Return(mockConn),
		mockConn.EXPECT().Do("GET", "posts").Return(`{"posts": []}`, nil).Times(1),
	)

	_ = posts
	_ = err
}
```

But I get an error:
> Unexpected call to *mocks.MockRedisPool.Get([]) at ... because: there are no expected calls of the method "Get" for that receiver

What am I doing wrong here?

**Comment by jon-whit** [comment]
@poy Worked like a charm! Thanks.
