### ISSUE TITLE
gomock_reflect_123456789 files are left and not deleted

### ISSUE THREAD

**Issue by hejnm1am** [golang/mock#264]
- Have file with //go:generate mockgen -destination mock_x/x.pb.go A/B/C/D/E/F YYY
- run go generate ./...
or alternatively run:
mockgen -destination mock_x/x.pb.go A/B/C/D/E/F YYY
from the same directory
- directory gomock_reflect_123456789 where 123456789 is random number is created and left

I am using go modules if it is important.

**Comment by poy** [comment]
It looks like we are removing the temp file via a defer:
https://github.com/golang/mock/blob/c20582278a829e4b3259747a3ce0eceb1763ee13/mockgen/reflect.go#L99

What version of gomock are you using? Can you also show me the output of `go env`?

**Comment by hejnm1am** [comment]
Go env here:

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxxx\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\xxxx\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\git\XXXX\YYYY\Src\ZZZZ\AAAA\BBBB\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxx\AppData\Local\Temp\go-build836306630=/tmp/go-build -gno-record-gcc-switches

I am using Go modules. I don't know if the name of Src directory in $GOMOD is important, but it has no relation to project dir. It is just name of directory if my git repo. Actual GO project is deep inside.

I don't know how to get version of gomock.
But I just run 'go install github.com/golang/mock/mockgen' and the problem is the same.
I installed mockgen no more than 14 days ago anyway.

**Comment by poy** [comment]
One thing I'm noticing is that the error returned from `os.RemoveAll(tmpDir)` is not being logged or anything. Can you build `gomock` from the [log-temp-remove-err](https://github.com/golang/mock/tree/log-temp-remove-err) branch? I've added logic to log the error if it fails to delete the temp directory.

**Comment by hejnm1am** [comment]
The branch log-temp-remove-err still point to the same commit as master.
Also there is no logging in  defer func() { os.RemoveAll(tmpDir) }() and no commit from time you wrote.

Can you please check you've pushed to the repo correctly?

**Comment by poy** [comment]
@hejnm1am Sorry about that. Should be fixed.

**Comment by hejnm1am** [comment]
2019/02/26 12:12:07 failed to remove temp directory: remove C:\xxx\yyy\gomock_reflect_422809967\prog.bin.exe: Access is denied.

Any hints how to find out why is access denied?

**Comment by poy** [comment]
I'm not an expert at windows. You might try to look into what policies you have and perhaps try moving your temp directory to a different location.

**Comment by hejnm1am** [comment]
I actually guess its some kind of race condition. Sometimes prog.bin.exe is deleted (so only empty directory remains) and sometimes not.

Also cannot this be because of I am using go with modules (go.mod)?
Other people using similar setup have same problems in my team.

I find my setup as a pretty default one.

**Comment by poy** [comment]
> I actually guess its some kind of race condition. Sometimes prog.bin.exe is deleted (so only empty directory remains) and sometimes not.

This is an interesting idea. So I've noticed that there is another place where a file is being removed:

https://github.com/golang/mock/blob/c20582278a829e4b3259747a3ce0eceb1763ee13/mockgen/reflect.go#L60

However, that temp file has a different prefix so I would expect them to be in different locations. Also that temp file is not `prog.bin.exe`.

> Also cannot this be because of I am using go with modules (go.mod)?

I wouldn't expect go modules would have any have any sway on a temp directory being removed.

Are you able to delete the temp directory manually?

**Comment by codyoss** [comment]
Closing due to age with no response. Please feel free to reopen if you have more details to share!
