### ISSUE TITLE
Mockgen installed with go modules cannot find own source

### ISSUE THREAD

**Issue by Helvind** [golang/mock#266]
I use go modules, and have followed the installation guidelines:

`go get github.com/golang/mock/gomock`
`go install github.com/golang/mock/mockgen`

But when I run `mockgen` it failes to find mockgen/models because it does not expect the source to be in the pkg/mod folder, but in src

**Comment by shreyashk2006** [comment]
@bhcleek: What was the resolution to this?

**Comment by rodoufu** [comment]
I've runned this:
```bash
$ go get github.com/golang/mock/gomock
$ go install github.com/golang/mock/mockgen
```

But when I try to find mockgen nothing is shown.
```bash
$ which mockgen
$
```

**Comment by poy** [comment]
Is $GOPATH/bin in your PATH?

**Comment by rodoufu** [comment]
> Is $GOPATH/bin in your PATH?

Yes, the big problem was when I tried to:
```bash
$ go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
```

I was getting:

> cd ~/go/src/github.com/golang/protobuf; git pull --ff-only
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> package github.com/golang/protobuf/proto: exit status 1

**Comment by CssHammer** [comment]
@Helvind have you found the solution?

**Comment by tommyjcarpenter** [comment]
I am still having this issue and the solution of `packages` did not fix it. 

In my case I am trying to bump `quay.io/goswagger/swagger:v0.23.0` to `quay.io/goswagger/swagger:v0.24.0` which leads to ```
# stash.corp.appnexus.com/devops-general/app_flotilla/models
../../models/cluster.go:230:12: undefined: validate.EnumCase
../../models/job.go:142:12: undefined: validate.EnumCase
../../models/job.go:185:12: undefined: validate.EnumCase
# stash.corp.appnexus.com/devops-general/app_flotilla/models
../../models/cluster.go:230:12: undefined: validate.EnumCase
../../models/job.go:142:12: undefined: validate.EnumCase
../../models/job.go:185:12: undefined: validate.EnumCase
prog.go:12:2: cannot find package "github.com/golang/mock/mockgen/model" in any of:
        /usr/local/Cellar/go/1.14.5/libexec/src/github.com/golang/mock/mockgen/model (from $GOROOT)
        /Users/tc677g/Development/go/src/github.com/golang/mock/mockgen/model (from $GOPATH)
prog.go:14:2: cannot find package "stash.corp.appnexus.com/devops-general/app_flotilla/worker" in any of:
        /usr/local/Cellar/go/1.14.5/libexec/src/stash.corp.appnexus.com/devops-general/app_flotilla/worker (from $GOROOT)
        /Users/tc677g/Development/go/src/stash.corp.appnexus.com/devops-general/app_flotilla/worker (from $GOPATH)
2020/07/22 08:58:17 Loading input failed: exit status 1
worker/cluster_manager.go:17: running "mockgen": exit status 1
make: *** [generate] Error 1
```

**Comment by fefi42** [comment]
I have the same issue

**Comment by DevilzOwn** [comment]
@tommyjcarpenter Were you able to find a solution for this? What was your workaround for this?
Why does it look into local directories for "github.com/golang/mock/mockgen/model" ?

**Comment by tommyjcarpenter** [comment]
@DevilzOwn unfortunately, I am no longer at the company with that codebase - it's been a couple of years about and I forget those details :(. Sorry!
