### ISSUE TITLE
Error output does not distinguish between nil slice and empty slice

### ISSUE THREAD

**Issue by briantkennedy** [golang/mock#267]
When comparing an expected arg with a nil slice to an actual arg with a zero length slice, mock concludes the two do not match, however, the output for 'want' and 'got' is exactly the same for the nil/emtpy slice and does not indicate where the mismatch occurred.

Example:
```
--- FAIL: TestNilVsEmpty (0.00s)
    example_test.go:24: Unexpected call to *mock_example.MockThing.Apply([0xc0000900a0]) at /usr/local/google/home/briankennedy/golang/work/src/github.com/briantkennedy/mockbug/pkg/mock_example/mock_thing.go:39 because: 
        Expected call at /usr/local/google/home/briankennedy/golang/work/src/github.com/briantkennedy/mockbug/pkg/example/example_test.go:19 doesn't match the argument at index 0.
        Got: &{[]}
        Want: is equal to &{[]}
    asm_amd64.s:522: missing call(s) to *mock_example.MockThing.Apply(is equal to &{[]}) /usr/local/google/home/briankennedy/golang/work/src/github.com/briantkennedy/mockbug/pkg/example/example_test.go:19
    asm_amd64.s:522: aborting test due to missing call(s)
FAIL
FAIL	github.com/briantkennedy/mockbug/pkg/example	0.021s
?   	github.com/briantkennedy/mockbug/pkg/mock_example	[no test files]
```

repository with code that reproduces issue: https://github.com/briantkennedy/mockbug

**Comment by poy** [comment]
@briantkennedy Would you expect the matcher to fail or return more informative information? For example, instead of saying:

```
&{[]}
```

return
```
<nil>
```

**Comment by briantkennedy** [comment]
For the case of comparing empty slice to nil slice, I'd expect a more informative message like "got: &{[]} want &{<nil>}" since there's subtle differences in the two.

**Comment by codyoss** [comment]
I think we should move this discussion to #190 @briantkennedy. It is not exactly the same, but I image the solution to one, could solve the other. It would be nice to collect these under one issue. If it is okay with you I would like to close this issue and move discussion there. WDYT?

**Comment by briantkennedy** [comment]
Yes, you're right, both of these sound like they should be solved together.  Let's make sure this case is captured there as well so both can be addressed when the time comes.

**Comment by codyoss** [comment]
I put your use case in that issue. Closing so we can have a unified discussion there. Thanks!
