### ISSUE TITLE
grpc stream mock

### ISSUE THREAD

**Issue by LucaPaterlini** [golang/mock#272]
hello while trying to mock this protocol I got this error
it seems to me that it's not able to find the gRPC package

mockgen -source=/home/pater92/Documents/work/Interview/Sea_LucaPaterlini/src/pipeProto/pipe.pb.go Transfer -destination=src/pipeProto/p_mock.go -imports grpc=google.golang.org/grpc
2019/03/09 18:37:33 Loading input failed: /home/pater92/Documents/work/Interview/Sea_LucaPaterlini/src/pipeProto/pipe.pb.go:193:2: unknown embedded interface grpc.ClientStream

how to sort this?

thanks in advance

https://we.tl/t-EdBeiZocxW 

I have added the proto in a zip

Tk in advance lp

**Comment by poy** [comment]
Hey! Sorry for the slow response. I don't feel great about downloading a zip file and opening it up. Any chance this is hosted via Github or something similar?

Are you using go modules? It doesn't look like `pipeProto/pipe.pb.go` is in the proper GOPATH.

**Comment by codyoss** [comment]
Closing due to age with no response. If you would like to put an example up on Github please feel free to reopen!
