### ISSUE TITLE
[BUG] Generated mock imports its own package

### ISSUE THREAD

**Issue by si-m** [golang/mock#274]
This started happening yesterday in the CI which installs a fresh version of `mockgen`. Then I ran `go get -u github.com/golang/mock/mockgen` and i could reproduced it locally.

The issue is that if i have two interfaces and one has a method that returns the other one, the generated mock file imports its own package, I doesn't realize that its in that same package.

The issue happens in source mode and reflect mode.

### How to reproduce the issue
`example package`
```go
package example

import "fmt"

type Foo interface {
	Foo()
}

type Bar interface {
	Bar() Foo
}

type a struct{}

type b struct{}

func (*a) Foo() {
	fmt.Println("foo")
}

func (*b) Bar() Foo {
	return &a{}
}
```

Create mocks for this package:
```
$GOPATH/bin/mockgen -package example -source=example/example.go -mock_names Foo=MockFoo,Bar=MockBar > example/example_mocks.go
```

**Comment by si-m** [comment]
Okay the `-destination` flag fixes my problem, but it was working fine a few days ago. It would be nice to have versions.

**Comment by balshetzer** [comment]
We do use versions. We haven't yet released a new version. You must be
following head.

**Comment by ghostsquad** [comment]
I don't understand. How do I ensure I have 1.20 installed instead of head? I'm having the same problem, and from the sound of this issue, there's something broken in head?

**Comment by wesmcnamee-avalara** [comment]
NVM - I looked at what others are doing, using `glide` or `dep` to vendor `golang/mock/mockgen`, then build/run the tool from that directory.
