### ISSUE TITLE
Add optional build tag to mockgen

### ISSUE THREAD

**Issue by titpetric** [golang/mock#282]
Mockgen should have an argument to specify optional build tag. If build tag is passed to mockgen, it should output this as the first line of the generated source file:

```
// +build [tag]
```

The value for [tag] could be a simple value like `unit` or `mock`, or a more complex one in line with go specifications (`!unit`, `unit,integration`,...). The type is `string`, no need to go deeper than that. The intent is to separate tests based on build tags.

**Comment by poy** [comment]
I'm not sure I see the use case. When would you not want the mock code included? In fact I believe if you don't use them, then the compiler will leave the types out.

**Comment by titpetric** [comment]
Yeah actually, my bad. (facepalm)

**Comment by tamccall** [comment]
one case i am running into is that my import paths might be different depending on which version of go you are using. is there any way we could reconsider this issue

**Comment by titpetric** [comment]
Seems valid, reopening to evaluate

**Comment by codyoss** [comment]
Please open a new issue /w new details. I would prefer an issue that has been closed for over a year stay closed. Thanks!

**Comment by loducapatricio** [comment]
I'd like to exclude the mock generated files from the final binary because they only have sense on tests context.

@codyoss Should I create a new issue of `Feature request`?

**Comment by codyoss** [comment]
@loducapatricio This is actually sort-of supported already today with the `copyright_file` flag. Just include a build constraint in the file referenced by that flag.

**Comment by loducapatricio** [comment]
Yes, I used `copyright_file` as a workaround.

```
mockgen -source ... -destination ... -copyright_file ${BUILD_TAGS_FILE}
```

And then I have a file:

```
+build unitTest
```
