### ISSUE TITLE
Upgrade to 1.3.1 fails

### ISSUE THREAD

**Issue by kishaningithub** [golang/mock#293]
The upgrade is failing like

```
go: finding github.com/golang/mock v1.3.1
go: github.com/golang/mock@v1.3.1: unknown revision v1.3.1
go: error loading module requirements
```

The problem i saw was the git tag for the new version is `1.3.1` instead of `v1.3.1` (You accidentally Missed the v there)

![Screenshot 2019-05-09 at 11 12 58 AM](https://user-images.githubusercontent.com/763760/57429917-9e921c00-724b-11e9-8d85-b5c0304f3573.png)

**Comment by poy** [comment]
Thanks! Fixed.
