### ISSUE TITLE
Mock unexported interfaces

### ISSUE THREAD

**Issue by syifan** [golang/mock#297]
It seems this question has been asked several times before like #29 #52. But I do not know the current solution to this problem. Or if this is even possible. So I am asking again. 

I have a few unexported interfaces and I have a few other functions use them. Here is a very simple sample code.

```go
package samplepkg

type printer interface {
    Print()
}

func AnotherFunction(printer Printer) {
    // Use the printer here
}
```

I need to test my `AnotherFunction`, which does not specify a concrete type of the printer, but the pinter is private and I do not want to export it. I wonder if there is a way to generate a mock for `printer`. 

There are two reasons I want to do this. First, I have internal implementations for the `printer` in the package, but since I am testing `AnotherFunction`, I do not want to touch the `printer` implementation. Second, I may not even have a concrete implementation for the printer, and the implementation should be provided by the library user. 

I am currently using a command like this to generate mocks.

```bash
mockgen -destination "mock_samplepkg_test.go" -package samplepkg -write_package_comment=false github.com/user/samplepkg printer 
```

**Comment by codyoss** [comment]
I will check this out, I assume it is a limitation of reflection though...

**Comment by nhoclove** [comment]
Is it possible to let us provide mock struct name when generating mocks for interfaces ? That way we can decide which mocks are exported/unexported.

**Comment by codyoss** [comment]
@nhoclove I would probably be resistant to this. I think the flag situation is already a little out of hand. If you don't want mocks exported in a public api I suggest using build tags to hide them or an internal folder.

**Comment by sonofachamp** [comment]
It seems including the `-source` flag will generate mocks for unexported interfaces.

**Comment by codyoss** [comment]
As mentioned, for now the guidance in this case is to use source mode.
