### ISSUE TITLE
Import cycle with v2 packages

### ISSUE THREAD

**Issue by syifan** [golang/mock#298]
I have a project that is has a v2 sub-directory like the following. 

```go
// File: github.com/user/samplepkg/v2
package samplepkg

type Printer interface{
}
```

When I run a `mockgen` like `mockgen -package samplepkg github.com/user/samplepkg/v2 Printer`, mockgen always import the v2 package with the name v2. I cannot even use `-self_package` to remove this import.

**Comment by codyoss** [comment]
Hey @syifan thanks for the report!

**Comment by codyoss** [comment]
Hey @syifan just had a chance to look into this. It appears to me that this is no longer an issue. I am going to close this for now. If you are still having issues please feel free to reopen the issue and please create a small repo to show me how to better reproduce this.
