### ISSUE TITLE
unsupported version of go when using go version go1.10.3 darwin/amd64

### ISSUE THREAD

**Issue by wNee** [golang/mock#301]
when I use ```mockgen -source=./contract.go -destination=./mocks/contract_mock.go -package=mock```
to generate mock impl. The error is: Loading input failed: unsupported version of go: exit status 2: flag provided but not defined: -compiled
Does it means that mockgen do not support go1.10.3

**Comment by balshetzer** [comment]
Gomock only supports the last two major versions of go. Right now that's
1.11.x and 1.12.x.

>
