### ISSUE TITLE
Deadlock when printing an error and mocking String()

### ISSUE THREAD

**Issue by mikdk** [golang/mock#302]
The gomock framework causes a deadlock when printing an error message containing a mocked object. The bug can be reproduced as follows using two interfaces, where the inner interface has a custom String() method:

```
type IInner interface {
	String() string
}

type IOuter interface {
	DoSomething(IInner) error
}
```

Now mockgen can be used to generate mocks for both interfaces. Consider the following test:
```
func TestMain(t *testing.T) {
	mockCtrl := gomock.NewController(t)
	defer mockCtrl.Finish()

	mockInner := mocks.NewMockIInner(mockCtrl)
	mockOuter := mocks.NewMockIOuter(mockCtrl)

	mockOuter.EXPECT().DoSomething(mockInner)

	mockOuter.DoSomething(nil)
}
```

Since the argument passed (```nil```) is clearly not the argument expected (```mockInner```), the gomock framework will try to print an error message while holding a mutex. This error message contains the arguments passed and expected, and thus invoke the mocked String() method on the Inner interface. This invocation will however try to acquire the same mutex, causing a deadlock.

**Comment by poy** [comment]
I think this issue brings up something I've been thinking about, why do we have locks? `testing.T` is not thread-safe. Are we properly supporting a use case by having these locks?

@balshetzer Do you have any historical context with this? Could we just remove the mutex?

**Comment by balshetzer** [comment]
The locks are there to make the mocks themselves thread safe.

**Comment by poy** [comment]
@balshetzer But why do the mocks need to be thread safe? If they ultimately go back and use an instance of `*testing.T` in non-thread safe manner, whats the point?

**Comment by codyoss** [comment]
I don't think there is an easy way to fix this. For now I am think we will go with no fix.

In general, I would say that is not good to use two layers of mocks at once. In this example I would suggest using a concrete type that implements `Outer`. As presented nothing is really being tested. I would consider re-opening if I was presented with a solid use-case of where mocking mocks provides value.
