### ISSUE TITLE
Mockgen on interface using cgo

### ISSUE THREAD

**Issue by undercover87** [golang/mock#303]
Hi, 
I'd like to generate a mock object for an inteface importing and using cgo, _i.e._ there are functions whose argument is C.some_type. 
The mock object is being generated alright (with mockgen) and naturally, "C" is also imported in the auto-generated mock file. 

But when I run go test I'm getting a **"cannot rename import "C" "** error message coming from the auto-generated mock file.

Is it possible to bypass this? Am I missing something?

thanks

EDIT: for clarity.

**Comment by poy** [comment]
Can you provide an example. (Disclaimer: I don't believe we support it nor am I confident we will.)

**Comment by codyoss** [comment]
Closing this for now because of no response and I am not sure about compatibility with cgo.... If you do respond with an example though feel free to reopen this!
