### ISSUE TITLE
unable to install mockgen following the instructions in README

### ISSUE THREAD

**Issue by dmitris** [golang/mock#308]
I'm unable to install `mockgen` following the instructions in https://github.com/golang/mock#installation:

```
$ go get -v github.com/golang/mock/gomock
github.com/golang/mock (download)
created GOPATH=/home/dmitris/go; see 'go help gopath'
github.com/golang/mock/gomock
$ go install -v github.com/golang/mock/mockgen
go/src/github.com/golang/mock/mockgen/parse.go:34:2: cannot find package "golang.org/x/tools/go/packages" in any of:
	/usr/local/go/src/golang.org/x/tools/go/packages (from $GOROOT)
	/home/dmitris/go/src/golang.org/x/tools/go/packages (from $GOPATH)
```

To make `go install` work, I had to also run:
`go get -v golang.org/x/tools/go/packages`.  Alternatively, the following command works:
`go get -v -u github.com/golang/mock/mockgen` - maybe we could use it instead of the current pair of `go get` and `go install`?

`go version` output: `go version go1.12.6 linux/amd64`

**Comment by poy** [comment]
Thanks for finding this!

I think this should be updated to a single step:
```
go get github.com/golang/mock/mockgen
```

We should probably also suggest you set `GO111MODULE=on` so that you use the `go.mod` file to grab the correct dependencies.

**Comment by Didin-e** [comment]
Mockgen **not working** for me using: `go install github.com/golang/mock/mockgen@v1.6.0`  i have Go ver:
`go version go1.18 linux/amd64`, even when i run  `which mockgen` No result

**Comment by jamestunnell** [comment]
> 

Same goes for me, I'm on `go version go1.18 linux/amd64` and 

> Mockgen **not working** for me using: `go install github.com/golang/mock/mockgen@v1.6.0` i have Go ver: `go version go1.18 linux/amd64`, even when i run `which mockgen` No result

Exactly the same for me.

**Comment by seda1094** [comment]
add `export PATH=$PATH:$(go env GOPATH)/bin` in .zshrc and try again
