### ISSUE TITLE
reflect mode failed while model.InterfaceFromInterfaceType print to os.stdout

### ISSUE THREAD

**Issue by rantibi** [golang/mock#31]
I run the following command :`mockgen matching  BannedDA` 
since it used reflect mode, it generate reflectProgram witch write the pkg to os.stdout, and then the mockgen try to read the resuld and decode it.

since I have init() method that print to std (using logrus logger) in part of my files, the stdout is not clean, and therefor the pkg can't be decoded in the following [line](https://github.com/golang/mock/blob/master/mockgen/reflect.go#L96), and the mockgen failed

I try to debug, and found that is [`{"BannedDA", reflect.TypeOf((*pkg_.BannedDA)(nil)).Elem()}`](https://github.com/golang/mock/blob/master/mockgen/reflect.go#L131) cause the init() call.

The point is the we can't trust stdout, and assume that it contains only the encode pkg,

**Comment by dsymonds** [comment]
Random packages should not be printing to stdout at init time. Log messages should be going to stderr anyway, but it's still obnoxious for packages to spam a program's output streams like that.

Fix your code and it should work.

**Comment by rantibi** [comment]
Well thats mean that if I use some third party (which I can't change) the write to stdout I can't use mockgen?

**Comment by dsymonds** [comment]
I guess so, yes. Such code would not be suitable in lots of circumstances.

**Comment by rantibi** [comment]
why not add some support for that?  (I can do it and open PR for that)
Thats mean I will print some result mark line before this [line](https://github.com/golang/mock/blob/master/mockgen/reflect.go#L150)
something like this `fmt.Println('\nPKG_RESULT')`
then [here](https://github.com/golang/mock/blob/master/mockgen/reflect.go#L93) I will read from then stdout until I find this mark line, and only then try to do the decoding.

what do you say?

(If not... I will have to fork it, which is something that really don't want to do)

**Comment by dsymonds** [comment]
Sorry, it's something that just isn't worth trying to work around. Libraries shouldn't be writing to stdout. File a bug against the library that's doing it.
