### ISSUE TITLE
how to mock specific function exists in my interface ?

### ISSUE THREAD

**Issue by RezaOptic** [golang/mock#311]
Hi,
i want to know how can i mock just some specific function in my interface.

for example i have this code and want to write some unit test for `Foo`.
```
type MainInterface interface {
	Foo(x, y int)
	Bar(x int) int
	Bar2(y int) int
}

func Foo(x, y int) int {
	return Bar(x) + Bar2(y)
}
func Bar(x int) int {
	return x * 2
}

func Bar2(y int) int {
	return y + 2
}
```

I just want to mock `Bar` and `Bar2`.
anybody have some solution for this ?

**Comment by poy** [comment]
We don't support this. Is there a reason having the other method (Foo) being generated is a problem?

**Comment by codyoss** [comment]
Closing due to no response recently. Please feel free to reopen if you would like to respond.
