### ISSUE TITLE
Returning another mock from a mock

### ISSUE THREAD

**Issue by hashcacher** [golang/mock#316]
I have a few interfaces to mimic some classes from consul (https://github.com/hashicorp/consul)
```
// consul_test.go
package consul

import "github.com/golang/mock/gomock"

func TestNew (t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mc := NewMockconsulClient(ctrl)
	mcc := NewMockconsulCatalog(ctrl)

	mc.
		EXPECT().
		Catalog().
		Return(mcc)

	consul, err := New(mc)
}
...
// consul.go
package consul

import "github.com/hashicorp/consul/api"

type consulClient interface {
	Catalog() *api.Catalog
}

type consulCatalog interface {
	Datacenters() ([]string, error)
}

func New(client consulClient) (*Consul, error) {
	catalog := c.client.Catalog()
	dcs, err := catalog.Datacenters()
        ...
}
```

Here's the error:
```
    consul_test.go:48: wrong type of argument 0 to Return for *consul.MockconsulClient.Catalog: *consul.MockconsulCatalog is not assignable to *api.Catalog [/Users/gregory/code/consul-go/pkg/consul/consul_test.go:47]
```
The error is referring to the `Return(mcc)`

Is there a workaround for this?

**Comment by balshetzer** [comment]
This is about the type system in Go. If a function is declared to return a
*consul.Catalog then the compiler will only allow it to return a
*consul.Catalog. if the function is declared to return an Interface that is
implemented by *consul.Catalog then you can either return a *consul.Catalog
or any other thing that implements the interface (i.e. a fake, stub, or
mock).

In this case, the Catalog function is declared to return a *consul.Catalog
so the mock has to return that. If you can change the type it returns to an
Interface implemented by *consul.Catalog then you can mock it out.

If you can use a real *consul.Catalog then try using that. If you can't or
need to make it behave differently in the test and need a mock then you
need the function to return an Interface so you can mock out the returned
object. If it's too late to change the return type of the function then....
I'm not sure.

**Comment by balshetzer** [comment]
I should have just said: make Catalog in consulClient return a
consulCatalog instead of a *api.Catalog. that'll fix it.

**Comment by hashcacher** [comment]
Your first paragraph about what the compiler accepts was very helpful, but when I change the consulClient Catalog() return type from *api.Catalog to consulCatalog, then I can't assign a "real" client to a consulClient variable anymore. i.e.
```
		client, _ := api.NewClient(&api.Config{
			Address: address,
		})
		var cclient consulClient = client // error! 
```
```
pkg/consul/consul.go:68:12: cannot use client (type *api.Client) as type consulClient in assignment:
	*api.Client does not implement consulClient (wrong type for Catalog method)
		have Catalog() *api.Catalog
		want Catalog() consulCatalog
```

Thanks for learning me a Go. I feel like I'm getting closer!

**Comment by hongrunz** [comment]
Hi @hashcacher just wondering if you ended up finding a way around this. I am having the exact same problem. Thanks!

**Comment by kelu-diao** [comment]
> 

@hongrunz you can simply cast the mock type to the original type in the `Return` parameter
