### ISSUE TITLE
Mockgen has so many flag,why not simplify it.

### ISSUE THREAD

**Issue by greyireland** [golang/mock#318]
There is so many flag,I have to do this.
`mockgen -source=client.go > mock_client.go` 
I wonder all flag set by default.just need
`mockgen .`

**Comment by greyireland** [comment]
find another mocker.
just do `mockery -all`

**Comment by codyoss** [comment]
Hey @greyireland sorry you thought there were too many flags. I think they are at least all pretty well documented. If you find that we could add some better docs please open another issue that is focused on an area we could improve.
