### ISSUE TITLE
bug: context.Background.WithCancel can't assignable to context.Backgroud

### ISSUE THREAD

**Issue by islishude** [golang/mock#320]
```golang
package main

import (
	"context"
	"fmt"

	"github.com/golang/mock/gomock"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	res := gomock.AssignableToTypeOf(context.Background()).Matches(ctx)
	fmt.Println(res) // fasle
}
```

**Comment by poy** [comment]
Yup, this looks like a bug. Thanks for filing it!

**Comment by poy** [comment]
After further review, it looks like what's going on is, `Context.Background()` is a `*context.emptyCtx` where as `ctx` is a `*context.cancelCtx`. So in fact, it should print `false`.

**Comment by islishude** [comment]
According to the documentation, 

> AssignableToTypeOf is a Matcher that matches if the parameter to the mock function is assignable to the type of the parameter to this function.

`Context.Background` is `context.Context` and `context.cancelCtx` is also `context.Context`.so `AssignableToTypeOf(context.Background())` should match `context.cancelCtx`.

```go
package main

import (
	"context"
	"fmt"
)

func main() {
	ctx := context.Background()
	ctxWithCancel, cancel := context.WithCancel(context.Background())
	defer cancel()
	ctx = ctxWithCancel // no error here
	fmt.Println(ctx.Err())
}
```

**Comment by islishude** [comment]
relates to #365
