### ISSUE TITLE
Delay called function to response

### ISSUE THREAD

**Issue by adzimzf** [golang/mock#322]
Is there a way to delay called function to give response?

**Comment by tscott0** [comment]
The [Do](https://godoc.org/github.com/golang/mock/gomock#Call.Do) and [DoAndReturn](https://godoc.org/github.com/golang/mock/gomock#Call.DoAndReturn) functions allow a stub implementation to be passed as a function. Example of Do [here](https://github.com/golang/mock/blob/22bbf0ddf08105dfa364d0a2fa619dfa71014af5/sample/user_test.go#L47).

I believe you could put a delay in this function to achieve what you need.

**Comment by adzimzf** [comment]
@tscott0 Thank you so much.
it works like a charm
