### ISSUE TITLE
When specifying -source, should ignore test files

### ISSUE THREAD

**Issue by fieryorc** [golang/mock#325]
When generating mocks with -source mockgen shouldn't include the test files. Here is why:

I have a package x and the following contents:

x.go
----

```go
package x

//go:generate mockgen -source x.go -destination x_gomock_test.go -package x

type Client interface {
	Invoke() error
}

type Service struct {
	C Client
}

func (s *Service) Do() error {
	return s.C.Invoke()
}
```

After this, I run `go generate ./src/x` and it generates the x_gomock_test.go file. So far so good. I write my test like this:

x_test.go
---------
```go
package x

import (
	"testing"
	gomock "github.com/golang/mock/gomock"
)

func TestServie(t *testing.T) {
	ctrl := gomock.NewController(t)
	mockClient := NewMockClient(ctrl)
	s := Service{C: mockClient}
	mockClient.EXPECT().Invoke().Return(nil)
	err := s.Do()
	if err != nil {
		t.Fatal(err)
	}
}
```

Now, I want to change the signature of the method Invoke() to accept string parameter. So I edit x.go and fix up everything. But mocks are out of date. Now I try to rerun `go generate ./src/x`, and I get the following error:

```
/usr/local/google/home/premram/src/orbitera/main/orbitera-v2/src/orbitera/test/x/x.go:13:20: too few arguments in call to s.C.Invoke
/usr/local/google/home/premram/src/orbitera/main/orbitera-v2/src/orbitera/test/x/x_test.go:12:18: cannot use mockClient (variable of type *MockClient) as Client value in struct literal: wrong type for method Invoke
/usr/local/google/home/premram/src/orbitera/main/orbitera-v2/src/orbitera/test/x/x.go:13:20: too few arguments in call to s.C.Invoke
2019/08/21 10:01:10 Loading input failed: loading package failed
src/orbitera/test/x/x.go:3: running "mockgen": exit status 1
```

What I expected:
-----------------
go generate succeeds because my sources compile fine. 

What I got:
-----------
go generate fails because mockgen includes test files while building the sources. Now I'm stuck in this state and the only way to fix is remove the test file and re-add it it. This workaround is acceptable for small package, but doesn't work on large code bases for following reasons:
1. There is no way to automate go generate part of the build
2. When doing refactor across large code base, this is super annoying.

**Comment by WIZARDISHUNGRY** [comment]
See also https://github.com/golang/mock/issues/275

**Comment by codyoss** [comment]
For now, a workaround would be to add a build tag to your test file. Such as `// +build ignore`

**Comment by codyoss** [comment]
With the latest release this now seems to work. Closing.
