### ISSUE TITLE
Mockgen fails when an import includes the major version

### ISSUE THREAD

**Issue by laconc** [golang/mock#326]
I'm importing `google.golang.org/api/storagetransfer/v1` in one of my source files and attempting to run mockgen on it results in:

```
Loading input failed: path/to/source.go:16:24: failed parsing returns: path/to/source.go.go:16:45: unknown package "source"
```
Adding an alias to the import such as `storagetransfer "google.golang.org/api/storagetransfer/v1"`, appears to resolve it, although Goland complains of a redundant alias.

I am using modules.

**Comment by codyoss** [comment]
Hey @laconc would you mind providing the command you are using to generate your mock?

**Comment by laconc** [comment]
Here you go:
```bash
mockgen -source=project-name/gcs/storagetransfer/storagetransfer.go -destination=project-name/gcs/storagetransfer/mocks/storagetransfer.go
```

**Comment by codyoss** [comment]
Thank you. I have not gotten a chance to test this out myself yet but it does sound like it could be a modules related issue. I will try to investigate further!
