### ISSUE TITLE
Error message is hard to understand

### ISSUE THREAD

**Issue by adzimzf** [golang/mock#327]
When the data type of expected result is different from the actual result, the error message needs to be more clear.

This error message a littel bit confusing when there's any changes on data type
```go
--- FAIL: TestRechargeModule_updateEnquiryBill/order_status_is_success_and_delete_redis_is_success,_and_update_bill_fulfillment_is_success_and_update_bill_status_is_failed (0.00s)
        enquiry_handler.go:30: Unexpected call to *mock_lib.MockEnquiryLibInterface.UpdateBillFulfillment([123 1 1]) at ../mocks/mock_src/mock_lib/mock_enquiry.go:66 because: 
            Expected call at ../enquiry_handler_test.go:154 doesn't match the argument at index 2.
            Got: 1
            Want: is equal to 1
```

it would be nicer if the error message is more clear 

if needed, I can create PR for this one

**Comment by codyoss** [comment]
Hey @adzimzf what would make it more clear in your opinion?

**Comment by adzimzf** [comment]
Hi @codyoss,
in my opinion, data type should mention in error message.
for instance, on the above sample I put, the difference is `int` and `int64` but since the value is equal, the error message would be better if it's like `Got: int(1)`, `Want : is equal to int64(1)`.

or is there any better idea?

**Comment by codyoss** [comment]
Thank you for your feedback. I will take your opinion into consideration as I ponder on this some more. Maybe we can get some more input from others in the community as well.

**Comment by adzimzf** [comment]
Thanks @codyoss

**Comment by codyoss** [comment]
Closing this as it seems to be a dup of #190 . Conversation for this will now happen there.
