### ISSUE TITLE
Proposal: Add method Wait to Controller

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [golang/mock#329]
Hi, probably that was already discussed or there's some common workaround for this problem, but i didn't found anything.

I have method with loop that reads events from channel. I want to close that channel when all expected calls to mock objects were made. Currently i run goroutine that sleeps for some time and then closes channel, it looks something like this:

```go
go func() {
    time.Sleep(20 * time.Second)
    close(ch)
}

testedMethod(ch)
``` 

Which is imperfect. What i would prefer is method `Wait(maxDuration time.Duration) (ok bool, err error)` that would wait before all expected calls were made,  with `maxDuration` as upper constraint.

**Comment by codyoss** [comment]
@GrigoriyMikhalkin If you are waiting to close the channel until your test is done could you use a `defer`? This seems like a specific use-case. I am not sure it would provide too much benefit for the library to handle this when the code to wait a a duration is trivial to write in most cases. I would say relying on timeouts for things usually leads to fragile/flaky tests. What do you think?

**Comment by GrigoriyMikhalkin** [comment]
>If you are waiting to close the channel until your test is done could you use a `defer`?
Problem is `testedMethod` running infinite loop that reads events from channel, so it's blocking. We want to wait until all test events are processed, and then close channel.

> This seems like a specific use-case. I am not sure it would provide too much benefit for the library to handle this when the code to wait a a duration is trivial to write in most cases.
That's fair. I don't see anyone else complaining about that, so probably issue can be closed.
