### ISSUE TITLE
Calling EXPECT().MinTimes(1).MaxTimes(1) / MaxTimes(1).MinTimes(1) is confusing

### ISSUE THREAD

**Issue by lukedirtwalker** [golang/mock#331]
The documentation says:

>  If AnyTimes or MaxTimes have not been called, MinTimes sets the maximum number of calls to infinity.

But if MaxTimes is called with argument 1 the MinTimes code considers this as MaxTimes has not been called yet.
See 
https://github.com/golang/mock/blob/dd8d2a22370e4c8a334e80ca8477f71356c8e4bb/gomock/call.go#L89-L91
and
https://github.com/golang/mock/blob/dd8d2a22370e4c8a334e80ca8477f71356c8e4bb/gomock/call.go#L99-L101

This is confusing and should either be fixed in the documentation or by adding a flag to check whether Min/Max-Times was called.

**Comment by codyoss** [comment]
Hey @lukedirtwalker sorry you found this confusing. This sounds like a docs update to me, are you interested in raising a PR?

**Comment by rkpatel7** [comment]
I can go ahead and update the documentation to reflect what the code is actually checking.

**Comment by codyoss** [comment]
That would be awesome @rkpatel7, the issue is yours!

**Comment by rkpatel7** [comment]
Thanks @codyoss! Hopefully my suggested update improves the clarity of the documentation.
