### ISSUE TITLE
Not working with Go modules

### ISSUE THREAD

**Issue by adithya66** [golang/mock#335]
Suppose, i have a go.mod file with some package name

#go.mod  
module example/examples

For local packages, mocked file is generated with 

import (
    x "."
)

instead of 

import (
    examples "example/examples"
)

**Comment by codyoss** [comment]
@adithya66 can you please provide a little more detail, including the command you ran. I am confused by what your issue is.

**Comment by codyoss** [comment]
Closing due to lack of response. Please feel free to reopen if you can provide some more details.
