### ISSUE TITLE
flag option for exclude private interface

### ISSUE THREAD

**Issue by adzimzf** [golang/mock#340]
I have a shell script that will scan all git changes, then generate it under `mocks` directory.
But, I have a problem with a private interface that returns a private variable. The private variable still generated, I wonder is there any way to exclude a private variable within `mockgen`.

**Comment by codyoss** [comment]
Hey @adzimzf can you please provide a small code snippet and the command you are running to generate your mock?

**Comment by adzimzf** [comment]
Hi @codyoss below is my code
```shell
curBranch=$(git branch | grep \* | cut -d ' ' -f2)

if [[ ${curBranch} = "master" ]] || [[ ${curBranch} = "staging" ]] ; then
    echo "Generate mock in master or staging branch is forbidden"
    exit 0
fi

go get -u github.com/golang/mock/...
go install github.com/golang/mock/mockgen

# get parent commit of this branch from master
parentCommit=$(git log --author="SyncToped" --max-count=1 --pretty=format:"%h" )

files=$(git diff $curBranch..$parentCommit --name-only & git diff --name-only | sort | uniq)
for file in $files;
do
    if [[ ${file} != "mocks"* && ${file} != *"_test"* && ${file} == *".go" ]]; then
        dest="mocks/$(echo ${file} | sed 's/^/mock_/; s/\//\/mock_/g')"

        if [[ ! -f ${file} && -f ${dest} ]]; then
            rm ${dest}
            git add ${dest}
            continue
        fi

        if [[ -f ${file} && $(cat ${file} | grep -i ".* interface {" | wc -l) -ne 0 ]]; then
            ${GOPATH}/bin/mockgen -source=${file} -destination=${dest}
            git add ${dest}
            echo -e "\e[0m${dest} is \e[32mgenerated"
        fi
    fi
done
```
it'll generate mock for all interface that changed.

**Comment by codyoss** [comment]
I would say for now if you only want a certain mock generated use reflect mode. In the future I would like the two modes to behave more similar(or there only need to be one way that just works). Closing for now.

**Comment by atombender** [comment]
I'd like to see this reopened. I have a file like this:

```go
package mypackage

type Scheduler interface {
  Schedule() error
}

type Option interface {
  configure()
}
```

For some reason, `mockgen -source myfile.go Scheduler` generates a `MockOption` even though it's not used and should not have a mock interface generated for it.

**Comment by codyoss** [comment]
@atombender Please see my previous comment on using reflect mode, example: `mockgen -destination mypackage_mock_test.go -package mypackage example.com/mypackage Scheduler`

Source mode will generate mocks for all interfaces in the file.

**Comment by atombender** [comment]
Yes, the issue still stands for source mode.

**Comment by atombender** [comment]
Perhaps for now it could simply do something like:

```
Warning: Emitting mocks for unrelated interface Foo (disable source mode to avoid this; see https://github.com/golang/mock/issues/340).
```

It would save people like me from wasting a lot of time googling for solutions.

**Comment by codyoss** [comment]
mockgen does not check to see if things are used, it just generates. I think this is explained in the [README](https://github.com/golang/mock#running-mockgen) the difference in behavior -- generating whole file vs a single interface. If you believe this could be explained better please open up a new issue with suggestions on how we could update some documentation.

**Comment by atombender** [comment]
This isn't explained in the readme at all, from what I can tell. And running this:

```sh
mockgen -source foo.go Foo
```

does not complain, even though apparently the extra argument is just ignored (or is equivalent to `Foo=Foo`). It's surprising that the two modes should behave so differently.
