### ISSUE TITLE
mockgen segfaults macOS 10.13.6 go 1.13.1 with signal ?

### ISSUE THREAD

**Issue by pavelz** [golang/mock#350]
tried to get back trace with gdb to no avail:
```
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin16.7.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mockgen...done.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /Users/pavel/.gopath/bin/mockgen.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /Users/pavel/.gopath/bin/mockgen
[New Thread 0xa03 of process 2542]
During startup program terminated with signal ?, Unknown signal.
(gdb) bt
No stack.
(gdb) trace
No default breakpoint address now.
(gdb) quit
```

**Comment by codyoss** [comment]
Can you please provide a small snippet with instructions of how to reproduce this issue?

**Comment by pavelz** [comment]
![image](https://user-images.githubusercontent.com/74142/69829541-77278e80-1231-11ea-938f-a13f90466493.png)

**Comment by codyoss** [comment]
Did you install go with Homebrew? I have seen some issues with users that have, and installing with the official installer fixes the issues. Have not figured out what it is about the Homebrew install yet...

**Comment by pavelz** [comment]
installed with go get. Running dlv I get an error as well:
```
$ dlv debug github.com/golang/mock/mockgen
could not launch process: decoding dwarf section info at offset 0x0: too short
```

**Comment by codyoss** [comment]
I meant is your version of go installed with Homebrew, sorry.

**Comment by pavelz** [comment]
no it was not.

**Comment by codyoss** [comment]
I don't have this version of the OS installed. But what I tried to test on, 10.14.6, seems to work fine. Adding a help wanted label on as this is hard for me personally to debug. If we could reproduce this in an environment that is easier to test against that would be helpful.(Docker, etc)

**Comment by codyoss** [comment]
@pavelz Can you please try downloading the current releases packaged binaries and see if that fixes your issue? https://github.com/golang/mock/releases/download/v1.4.1/mock_1.4.1_darwin_amd64.tar.gz

**Comment by codyoss** [comment]
Closing due to lack of response. Please re-open if this is still an issue /w provided binaries.
