### ISSUE TITLE
Avoiding import cycle in packages with more than 1 interface 

### ISSUE THREAD

**Issue by rubens21** [golang/mock#352]
I am creating a package that contains two interfaces, and one of them uses the other one.
Example:
```go
package foo

type A interface{
... some stuff here
}

type B interface{
 DoSomething() A
}
```
I have tested several options to avoid import cycle, but all of them bring me some issues:

# Option 1 
including the mocks in test files
```
/foo
  -- a.go
  -- b.go
  -- some_test.go
  -- mock_test.go
```
### Problem
The mocks are not shared with other packages in my project.

# Option 2 
Keeping the mocks in other libs and writing tests files in the same package name
```
/foo
  -- a.go
  -- b.go
  -- some_test.go (package "foo")
/testdata
  -- mock_b.go
```
### Problem
There will be an import cycle because `some_test` is part of `foo` and it needs to include `testdata`.
Test data includes `foo` even if I only generated a mock for `B`.

# Option 3 
Keeping the mocks in other libs, **but writing tests files in "_test" package**
```
/foo
  -- a.go
  -- b.go
  -- some_test.go (package "foo_test")
/testdata
  -- mock_b.go
```
### Problem
I will not be able to test non exported elements in `foo` since they are not visible on `foo_test` package. It would require me to only make integration tests.

# Option 4
Declaring the interface in a isolated folder
```
/foo
  -- /interfaces 
     -- a.go
     -- b.go
  -- ab_source.go (where the interfaces would actually be implemented)
  -- some_test.go (package "foo")
/testdata
  -- mock_b.go
```
### Problem
That works fine, but it is not idiomatic, and the package usage would be confusing.
Example: `foo.NewA()` would return an interface `interface.A` and there would not be a meaningful name for the "interface" package.

 # Option 5
Exporting the mock as part of the project 
```
/foo
  -- a.go
  -- b.go
  -- some_test.go
  -- mocks.go <---- Note that there is no `_test` suffix
```
### Problem
The final binary will be bigger than the necessary, what could not be a big issue, but I guess it is also not idiomatic. 

I am wondering how you guys solved this issue on your project since I could not find many comments about it. 

I found some people with import cycles, but they were related to other issues.

**Comment by cvgw** [comment]
@rubens21 is this using `-source` mode?

**Comment by rubens21** [comment]
No, I was not using source mode.
But I don't think it would affect the final result. Would it?

**Comment by cvgw** [comment]
@rubens21 is using source mode an option for you?
Using source mode plus the flags `self_package` and `package` I can generate code that correctly specifies `DoSomething() A` rather than `DoSomething() foo.A`

**Comment by rubens21** [comment]
Would it be correct?
I mean, whatever is using the mock will expected `foo.A`, not `mock.A`.
I will test it out and answer you here.
Thank you, though

**Comment by rubens21** [comment]
Never mind, both interfaces would be identical anyway :p I will try.

**Comment by cvgw** [comment]
Sorry, I should have been more clear. My above suggestion was assuming you put the mocks in `pkg Foo`. So at that point `A` would indeed refer to `foo.A`

**Comment by rubens21** [comment]
Hi @cvgw , sorry for late response.

I tested your suggestion, but `mockgen` is creating the mocks as expected in all attempts.
It imports the original package **only** when the second interface requires it (e.g. as an argument).
And it makes sense. The interface B needs to refer to the original package anyway.
 
I created a demo repo at https://github.com/lugobots/demo-issue-mocks to show how I am creating the mocks (please see read me file and mocks in `testdata` folder).

My original question is regarding having a good approach to keep the code organised and idiomatic.

**Comment by cvgw** [comment]
@rubens21 I apologize for the confusion; I think the examples in that repo are different than what I was suggesting. My suggestion was to do something like this
`mockgen -package=bar -destination=bar/mocks1.go -source=bar/interfaces.go -self_package=mydemo/bar`

Perhaps I am misunderstanding your goal. My impression is that you want to generate the mocks in such a way that
1. You don't need to put the mocks in separate files
2. You don't need to put your tests in `*_test` pkg
3. That there are no circular dependencies

I believe the command above would satisfy all of those as it will create the mocks in pkg `bar` and will have no circular dependencies.

**Comment by rubens21** [comment]
oh, I see.
Yeah, but the question was kind of a request for a suggestion regarding best practices.
As you see, the option 4 was doing that. However, since the file does not the `_test` suffix, I believe it will be part of the compiled package. 

It is not a big issue, that's actually how I am doing it in my projects, but I don't know if it is idiomatic.

Thank you for you help, though .

**Comment by cvgw** [comment]
@rubens21 I'm sorry I may be confused, did you mean option 5 in your original comment? Neither of the option 4 you shared write the mocks to the src package.

And I do think it's idiomatic; any thoughts on why it wouldn't be? I don't think I've ever seen a case where the mocks wouldn't be part of the final compilation.

**Comment by cvgw** [comment]
Though, thinking about it now `mockgen -package=bar -destination=bar/mocks1_test.go -source=bar/interfaces.go -self_package=mydemo/bar` might allow the mocks to be excluded from the final compilation. Not sure if that is more idiomatic though.

**Comment by rubens21** [comment]
Thank you.
Good to know it is not a bad practice.
Yeah, I was talking about the option 5.

The problem with having the mocks in a test file (`_test`) is that I cannot use the same mocks to test other packages.

Thank you again, @cvgw 
Can I close the question? The questions is answers from my perspective.

**Comment by cvgw** [comment]
Ya, feel free to close. Thanks for opening this issue; I'll add any issue to include some more info on how to best handle these kinds of scenarios.

**Comment by powerman** [comment]
There is annoying issue with Option 5 (interface, implementation, mock and tests all in same package).

After making some changes to the interface and related changes to it implementation I need to update tests… but at this point tests don't compile because previously generated mock doesn't match current interface anymore. So, I run `go generate`… and it fails because of compilation errors in tests.

To work around this issue sometimes it's enough to delete generated file with mocks before running `go generate`, sometimes it's not enough and I need to temporary remove all `*_test.go` files from this package before running `go generate`.

**Comment by digglife** [comment]
Eventually I used option 4, but the naming is a headache indeed. ☹️
