### ISSUE TITLE
mockgen outputs a True file - how to silence / stop generating this file

### ISSUE THREAD

**Issue by JCzz** [golang/mock#356]
Hi

I have a perfect mock generated, but it outputs a "True" file. Is it possible to silence this?

I just expect it to be a log, saying everything went ok.

**Comment by codyoss** [comment]
Hey, I am not sure I follow what you are saying. Could you give a small example? What do you mean by 'True file'?

**Comment by JCzz** [comment]
@codyoss  I will close this, my mistake - I found that it was in my script! 
Thanks for you replay
