### ISSUE TITLE
Add repo automation via bots

### ISSUE THREAD

**Issue by cvgw** [golang/mock#360]
I suggest we add the following bots
* [delete merged branches](https://probot.github.io/apps/delete-merged-branch/)
* [triage new issues](https://probot.github.io/apps/triage-new-issues/)
* [close issues after no response](https://probot.github.io/apps/no-response/)
* [comment on issues which are blank or haven't filed out the template](https://probot.github.io/apps/request-info/)

If some of these don't seem right or we don't want to add them all at once that's ok with me.

**Comment by cvgw** [comment]
cc @codyoss

**Comment by cvgw** [comment]
Also [closing stale issues and pull requests](https://github.com/apps/stale)

**Comment by codyoss** [comment]
I would really like to get some of this automation in place too. I will have to ask around a bit though as to rules for adding bots to this org. I assume we have to jump through some extra hoops.

**Comment by cvgw** [comment]
Ahh didn't even think about whether bots would have to be added to the org. I know there is some similar automation that other projects are using in the org so if we can't use these bots maybe we can utilize what others are.

**Comment by codyoss** [comment]
Yeah, I would think at the bare minimum we could make use of the one already around.

**Comment by codyoss** [comment]
As for the bots suggested in this post:

1. delete merged branches
  - This is just a setting in Github now, I have turned this on.
2. triage new issues
  - I am not sure this one could provide too much value. I think this is valuable maybe only for feature requests? And I have added to the template auto tag that one. Auto tagging bugs I intentionally left off as in my experience many issues are opened as bugs, but are really just a question or misunderstanding. Thoughts?
3. close issues after no response
  - I really like the idea of this one. I did make a `needs more info` tag. Would be cool if a bot could close things after an issue has been tagged and there has been no response in x days.
4. comment on issues which are blank or haven't filed out the template
  - There is a setting to force the use of templates. Should we turn that on? Sure someone could open the template and delete it all, but for the most part I _assume_ people will use it now that it is there. Time will tell
5. closing stale issues and pull requests
  - sounds similar to 3. SGTM

Additionally I would eventually like to see:

1. A release proposal bot. Gathers commit messages, update a changes.md or release notes. Upon merge tag and update a binary with the release. 
2. Freeze closed issue bot. Freeze old closed issues so an issue closed a year ago does not get suddenly opened again.


I think bots stuff, as long as we can get through any red tape, would make a good milestone/epic to track.

**Comment by codyoss** [comment]
Closing this issue for now. May open up individual issues in the future is automation is need for each specific usecase.
