### ISSUE TITLE
Integrate benchmarks with CI

### ISSUE THREAD

**Issue by cvgw** [golang/mock#373]
*Requested feature* A clear description of the desired feature and an example of
how it would be used.

Benchmarks should be run and have some kind of assertion/validation during CI

*Why the feature is needed* A clear description of how this feature is not
served by existing functionality in gomock.

To ensure that there are no major performance regressions

*(Optional) Proposed solution* A clear description of a proposed method for
adding this feature to gomock.
 possible option https://dev.to/dannypsnl/how-to-compare-go-benchmark-in-travisci-2407

**Comment by codyoss** [comment]
Closing this issue for now. There are open issues around performance. If we see some issues arise in the future will re-evaluate.
