### ISSUE TITLE
EXPECT uses always first return value when used AnyTimes()

### ISSUE THREAD

**Issue by micharaze** [golang/mock#402]
**Actual behavior**
When I am using the following line multiple times with different return objects then the mocked function returns always the object like expected:
```
mock.EXPECT().DoSomething(gomock.Any(), gomock.Any()).Times().Return(someObject1, nil)
// DoSomething() returns the object someObject1
mock.EXPECT().DoSomething(gomock.Any(), gomock.Any()).Times().Return(someObject2, nil)
// DoSomething() returns the object someObject2
```
But if I change the Times() call to AnyTimes(), then it returns always the first given return object:
```
mock.EXPECT().DoSomething(gomock.Any(), gomock.Any()).AnyTimes().Return(someObject1, nil)
// DoSomething() returns the object someObject1
mock.EXPECT().DoSomething(gomock.Any(), gomock.Any()).AnyTimes().Return(someObject2, nil)
// DoSomething() returns the object someObject1
```

**Expected behavior**
I expected, that it should return the new set return object like it is doing on the first example with Time().

**Comment by codyoss** [comment]
If I had to guess without looking at the code I would say it is because AnyTimes() is greedy. There is no reason for it to move on to the second mock because nothing new has changed and the first EXPECT is still doing its work. I believe this is expected behavior. Thoughts?

**Comment by micharaze** [comment]
In my case I created a sub-function to easily create different test cases. It happens that the mocked function is not called in every case. I don't care how often the function is called, because I'm testing error cases. I wanted to create the mock controller only once and reuse it with every call. But now I have to create a new controller every time.

**Comment by codyoss** [comment]
This is working as expected. The only way you can you can AnyTimes the same mock is if you use InOrder and have a mock in between:

```go
	gomock.InOrder(
		mock.EXPECT().Foo().AnyTimes().Return("one"),
		mock.EXPECT().Bar().AnyTimes().Return("two"),
		mock.EXPECT().Foo().AnyTimes().Return("three"),
	)
```

**Comment by Yuu177** [comment]
> In my case I created a sub-function to easily create different test cases. It happens that the mocked function is not called in every case. I don't care how often the function is called, because I'm testing error cases. I wanted to create the mock controller only once and reuse it with every call. But now I have to create a new controller every time.

My situation is the same as yours. How did you solve it

**Comment by Yuu177** [comment]
> In my case I created a sub-function to easily create different test cases. It happens that the mocked function is not called in every case. I don't care how often the function is called, because I'm testing error cases. I wanted to create the mock controller only once and reuse it with every call. But now I have to create a new controller every time.

Has your problem been solved?
I did like this, but it can not return what I expect in my test sub-function.
```go
gomock.InOrder(
		mock.EXPECT().Foo().AnyTimes().Return("one"), // return "one"
		mock.EXPECT().Bar().AnyTimes().Return("two"),
		mock.EXPECT().Foo().AnyTimes().Return("three"), // return "one".
	)
```

**Comment by suber124** [comment]
> If I had to guess without looking at the code I would say it is because AnyTimes() is greedy. There is no reason for it to move on to the second mock because nothing new has changed and the first EXPECT is still doing its work. I believe this is expected behavior. Thoughts?

Appreciate!
