### ISSUE TITLE
Vendor import

### ISSUE THREAD

**Issue by yonesko** [golang/mock#408]
**Describe the Bug**
I have generated a mock and import path in it `"olol-olololol/vendor/go.avito.ru/gl/service-phones-client"`.
The test doesn't compile with error 
```
imports ololololo/vendor/go.avito.ru/gl/service-phones-client: must be imported as go.avito.ru/gl/service-phones-client
```
**Expected Behavior**
Correct import `go.avito.ru/gl/service-phones-client` with which test is complied.

**Migrate Version**
dev

**Go Version**
go version go1.13.8 darwin/amd64

**Comment by codyoss** [comment]
Thanks, for the report. Could you please provide a small sample to show how to reproduce this?

**Comment by codyoss** [comment]
Closing due to lack of response. Please feel free to re-open if you can share more details.
