### ISSUE TITLE
How to get all the mockgen dependencies in a docker image.

### ISSUE THREAD

**Issue by lauatic** [golang/mock#409]
**Actual behavior** A clear and concise description of what the bug is.

I want to build a docker image with this Dockerfile for running the mockgen.  The GOPATH is /go inside the container when I "docker run" the image generated from this Dockerfile.  The issue I'm facing is that it is downloading the mockgen's related dependencies every time I "docker run" the image.  I tried with "docker mod download" in the Dockerfile and that did not help.

After the "go get .../mockgen@1.4.1", is there a way to pull the rest of the dependencies inside the image so that the container run does not need to download dependencies everytime?  I also tried with "go get -a ...".

```
FROM golang:1.14

ENV GO111MODULE=on

# install mockgen
RUN go get -u github.com/golang/mock/mockgen@v1.4.1

# Download the dependencies
# RUN go mod download

# ENTRYPOINT ["mockgen"]
```

**Expected behavior** I want to avoid the downloading mockgen dependencies every time I run mockgen through the docker image.

**To Reproduce** Steps to reproduce the behavior

1.  ...
2.  ...

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version or git ref: v1.4.1
-   golang version: go version go1.14 linux/amd64
**Triage Notes for the Maintainers**

**Comment by codyoss** [comment]
Have you considered just downloading one of the binaries we publish? https://github.com/golang/mock/releases/tag/v1.4.1

**Comment by lauatic** [comment]
> Have you considered just downloading one of the binaries we publish? https://github.com/golang/mock/releases/tag/v1.4.1

Thanks for your suggestion.  I downloaded the tar.gz file and put mockgen in /usr/local/bin/ directory.  It looks like it is still doing the same "download" dependencies.  Are there other things I have overlooked?
```
ENV MOCK_VER 1.4.1
ENV MOCK_URL https://github.com/golang/mock/releases/download/v${MOCK_VER}/mock_${MOCK_VER}_linux_amd64.tar.gz

RUN mkdir -p /tmp/mock && \
    wget -P /tmp/mock ${MOCK_URL} && \
    cd /tmp/mock && \
    gunzip < mock_${MOCK_VER}_linux_amd64.tar.gz | tar xf - && \
    cp mock_${MOCK_VER}_linux_amd64/mockgen /usr/local/bin && \
    rm -rf /tmp/mock

ENTRYPOINT ["/usr/local/bin/mockgen"]

```

**Comment by codyoss** [comment]
I guess I am having a hard time understanding what problem you are having. Can you give me step-by-step what you are doing and what you expect? Thanks.

**Comment by codyoss** [comment]
Closing due to lack of response. Please feel free to reopen if you can provide more details.
