### ISSUE TITLE
mockgen: prog_only mode ignoring write error

### ISSUE THREAD

**Issue by blico** [golang/mock#411]
We are facing an issue where `mockgen -prog_only ...` is exiting successfully, but outputting an empty file.

In our repo's build system (Bazel), the call to `mockgen -prog_only` is a cacheable build action. Not returning a failure in the case mentioned becomes problematic because Bazel caches the build action's output whenever the underlying command succeeds (returned an exit code 0). Meaning when `mockgen` fails to write to `stdout` and does not exit with a failure, we end up uploading an incorrect build artifact to our cache.

**Comment by codyoss** [comment]
Seems reasonable to me. Thanks.
