### ISSUE TITLE
Ability to generate mocks for multiple packages

### ISSUE THREAD

**Issue by tartale** [golang/mock#412]
*Requested feature* 
Add the ability to generate mocks for more than one package at a time, within one call of the executable.

*Why the feature is needed* 
Currently, mock generation is limited to one package per call of the executable.  The initialization of the executable over and over for a large number of packages takes time, and allowing the ability to execute the program once would save time/resources.  If `mockgen` is used exclusively through `go generate` calls, this not be a helpful optimization.

*Proposed solution* 
Add a command-line option to input and process a text file that lists out the parameters for multiple calls to `mockgen` (one per line), to prevent invocation of the executable multiple times.  The `mockgen` tool can then iterate through the lines in that file, processing it as if each line was specified as the CLI of a single call.

Example:
input.txt
```
--destination <path> --package <package-1> <source-path-1> <interface-1,interface-2,...> 
--destination <path> --package <package-2> <source-path-2> <interface-1,interface-2,...> 
...
```

CLI
```
mockgen --input-file input.txt
```

**Comment by codyoss** [comment]
As you pointed out a good way to get around this is by using `go generate` directives in multiple files. Another way, that would operate similar to your suggestion, would be to just wrap the generation is a script and generate all of the files.

**Comment by codyoss** [comment]
After some more thought I don't think we support this right now for the reasons stated above. If you have more ideas for mock though please don't hesitate to open more issues.

**Comment by tartale** [comment]
> After some more thought I don't think we support this right now for the reasons stated above. If you have more ideas for mock though please don't hesitate to open more issues.

ok - I'm a little confused by the reply, but the suggested workarounds to put the `go generate` directives in multiple files, or to wrap generation in a script are not at all workarounds for the issue I was describing.

To clarify, we have many many packages, and we need to call `mockgen` once per-package.  Each call takes about .5 second to complete, so this extends the build quite a bit.  I'd like to be able to make one call to `mockgen` for many packages/interfaces, to save time (hence, the feature request).

I'm okay to leave this closed for now; I just wanted to clarify the request

**Comment by qdm12** [comment]
Also adding to this, I like to have a single mock file `mocks_test.go` per package holding all my mocks, and that becomes not possible as soon as I need to generate mocks from 2 different packages. I tend to define package-local interfaces to workaround this, but it would be nice to support this somehow.
