### ISSUE TITLE
Failed parsing when the parameter type is parenthesized.

### ISSUE THREAD

**Issue by Krout0n** [golang/mock#416]
**Actual behavior**
`example.go`
```go
package example

type Example interface {
	ParenthesizedParameterType(param (int))
}
```

Result:
`Loading input failed: parenthesized.go:4:28: failed parsing arguments: don't know how to parse type *ast.ParenExpr`

**Expected behavior** 
The above codes are accepted.
https://golang.org/ref/spec#Types
> Type      = TypeName | TypeLit | "(" Type ")" .

**Additional Information**
-   gomock mode (reflect or source):
-   gomock version or git ref:
```
$ mockgen -version
-> v1.4.3
```
-   golang version:
```
$ go version
-> go version go1.14.1 darwin/amd64
```

**Triage Notes for the Maintainers**
I know the linter removes these parentheses. But in case of `*(<typename>)`, it doesn't.
And if this wasn't so hard, I'd be up for the challenge.

**Comment by codyoss** [comment]
Seems reasonable, I guess I did not know this was even in the spec, thanks for teaching me something!

**Comment by akhiljain23** [comment]
I am still getting a similar error,
My use case is
`type A interface {
	Binterface
	someFunc(ctx context.Context, limit, skip int, somStr string) (*([]SomeStruct), int, error)
}`
Output on mockgen
`mockgen -source file1.go -destination file1_mock.go  -package pkg1 -aux_files=github.com/something/something=something.go
2020/08/27 23:09:29 Loading input failed: something.go:20:15: failed parsing returns: don't know how to parse type *ast.ParenExpr`
