### ISSUE TITLE
Add If method on Call for conditional EXPECT

### ISSUE THREAD

**Issue by bogatuadrian** [golang/mock#417]
*Requested feature*
Register an expected call (or not) based on a condition.

Example:
```go
mock.EXPECT().Foo().If(call == true)
```

*Why the feature is needed*
A common use case, especially when table-testing, is to parametrize behaviour. This feature would come in handy when you have multiple expected calls that depend on one another in the tested code. Status quo example:
```go
mockA.EXPECT().Foo().Return(test.aErr)
// Bar() is called only if Foo() succeeds in the tested code.
if test.aErr == nil {
	mockB.EXPECT().Bar().Return(test.bErr)
}
```

It would be cleaner to write:
```go
mockB.EXPECT().Bar().Return(test.bErr).If(test.aErr == nil)
```

Even though the Go `if` works just fine, and I'm not a proponent of code golf especially in Go, I feel that this feature fits with the current `Call` API and could make the tests intentions a bit clearer.

*Proposed solution*
At first glance, this seems to be easily implemented using `Call.minCalls` and `Call.maxCalls`, similar to the `Call.Times()` implementation. There might be some corner cases when calling `.Times(n).If(b)` or `.If(b).Times(n)`.

Let me know what you think. I'm up for implementing this feature myself `.If(👌)`.

**Comment by codyoss** [comment]
I am not sure if it is cleaner. It does save some lines of code, but in my opinion hurts readability.  I think most developers have trained their eyes to look for conditions, this hides that conditional a little more.

**Comment by eliashanna9** [comment]
what happened to this feature? I think it would be cool too, it's marked as completed..
