### ISSUE TITLE
using vendor folder 

### ISSUE THREAD

**Issue by thynquest** [golang/mock#426]
Hello 

I am reopening this issue which has already been [discussed](https://github.com/golang/mock/issues/296) without being resolved. Is there a way for mockgen to use then vendor folder instead of downloading the dependencies. In my case I am trying to generate mocks using docker container. so at the end of the dockerfile I have this 
`ENTRYPOINT ["sh", "-c", "/usr/local/bin/mockgen -source=${INPUT_FILE} -destination=${OUTPUT_FILE} -build_flags=-mod=vendor"]`  but it does not work since it keeps trying to download the dependencies and some of them are private.

Is there a way to fix/workaround this ? 

Thank you for your help

**Comment by codyoss** [comment]
Before I look more into this, can you please tell me what version of Go you are using and what version of mockgen?

**Comment by thynquest** [comment]
hello and thank you for your answer
I am using `go version go1.12.9` and `mockgen 1.4.3`

**Comment by nguyenfilip** [comment]
@thynquest what is the working directory when `mockgen` gets run? Is it the same directory where `vendor` resides? I recently created a small sample docker image that uses vendoring here: 
 https://github.com/nguyenfilip/mockgen-docker 

On top of what you are trying to achieve the example uses `go:generate mockgen`. 

Could you provide a running reproducer with sample vendor folder?

**Comment by codyoss** [comment]
Closing due to lack of response. Please let me know if you are still having this issue and we can reopen this.
