### ISSUE TITLE
Type-safe return values

### ISSUE THREAD

**Issue by jtyers** [golang/mock#427]
*Requested feature*
I have recently moved from `testify/mockery` to using GoMock for generating mocks, and simply having the mock aware of the types of my calls is great.

However, the arguments for `Return()` are always `interface{}`. Can gomock generate mocks that `Return` with types that match the underlying method?

This would make refactoring existing code a bit easier as invalid types returned from mocks would be straight compile errors rather than test failures, thus failing faster and with (imo) a clearer error message.

**Comment by codyoss** [comment]
Return operates on a `Call` today, which is what is returned by all of stubbed out methods. With how this library is currently designed, I don't this we can accommodate this request. If you have a concrete suggestion about how to implement this please feel free to reopen. Thanks.

**Comment by robsonpeixoto** [comment]
@codyoss maybe [minimock](https://github.com/gojuno/minimock) is a good inspiration.

**Comment by Trim21** [comment]
@codyoss We can add a stub type in generated code to accomplish this:

```golang
type TypedCall struct {
	*gomock.Call
}

func (t *TypedCall) Return(typedReturn1 int, typedReturn2 error) *gomock.Call {
	return t.Call.Return(typedReturn1, typedReturn2)
}

func TestTypeSafeReturn() {
	m := &TypedCall{nil}
	m.Return() <-- Compile time error
}
```
