### ISSUE TITLE
Should `Finish` be run in a deferred way or not?

### ISSUE THREAD

**Issue by owen-mc** [golang/mock#431]
I noticed that there is a call to `recover` in `Finish` in `/gomock/controller.go`. I've recently learned that `recover` is only useful in a deferred function - outside of them it has no effect [1]. So I checked if `Finish` is called in a defer statement. Your advice was to do that, but then with go1.14+ you said that the user doesn't need to call `Finish` because `gomock` does it for them. That's in `NewController` in `gomock/controller.go`. But it isn't called in a defer statement, so `Finish` no does everything before the `recover` call when the goroutine is panicking. Was that slight change in behaviour deliberate? It seems to me it would be possible to make it a defer statement and restore the old behaviour.

[1] "Recover is only useful inside deferred functions." https://blog.golang.org/defer-panic-and-recover

**Comment by codyoss** [comment]
These are some good points. Can you please provide a small example of before and after that commit. That feature has not been released yet so if there are some issues I would like to get them sorted out soon. Thanks for the report.

**Comment by owen-mc** [comment]
I'm afraid I don't have enough context to do that easily because I'm not a user of golang/mock. I was testing out a new check I'd added to a static analyser, and checking whether the hit I got for this repo was a true positive or a false positive. In theory it should be a case of writing a test which panics and trying it out with the old and new style. Looking at the code in `Finish` it seems that the only substantial this is  it would caller `Helper()` on `T`, the `TestReporter` that is passed in. You probably know better than me whether that could do anything significant.

**Comment by codyoss** [comment]
The cleanup function itself is deferred so this should be okay.

**Comment by owen-mc** [comment]
If a deferred function calls a function, the state of being in a panic doesn't get carried into that function. It's very easy to misunderstand this, hence why I was adding the check to my static analysis tool. It's hard to explain clearly in words, so here is some example code. Ask yourself if it will print "recovered in a" or "recovered in b".

```
package main

import "fmt"

func b() {
  defer func() { if recover() != nil { fmt.Printf("recovered in b") } }()
}

func a() {
  defer func() {
    b()
    if recover() != nil {
      fmt.Printf("recovered in a")
    }
  }()
  panic("error")
}

func main() {
	a()
}
```

It prints "recovered in a" - try running it if you don't believe me! I didn't believe it when I first saw it. The reason is that when there is a panic, and execution goes into a deferred function, when a normal function (`b` in this case) is called from that deferred function the state of being-in-a-panic isn't carried down the call stack. It only ever propagates up the call stack.
