### ISSUE TITLE
The imports flag has no effect

### ISSUE THREAD

**Issue by piersy** [golang/mock#436]
**Actual behavior**

Providing explicitly named imports with the imports flag does not affect the generated mock.

**Expected behavior** 

I would expect the named imports to be used in the mock.

**To Reproduce** Steps to reproduce the behavior
1. cd to your go installation src dir.
2. Run `mockgen -source=io/io.go -imports foo=io,bar=math   | head -n 15`
3.  Observe the output does not include the named imports.
```
// Code generated by MockGen. DO NOT EDIT.
// Source: io/io.go

// Package mock_io is a generated GoMock package.
package mock_io

import (
	gomock "github.com/golang/mock/gomock"
	io_go "io/io.go"
	reflect "reflect"
)

// MockReader is a mock of Reader interface
type MockReader struct {
	ctrl     *gomock.Controller

```

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version: v1.4.3
-   golang version: go1.14.2 linux/amd64

**Comment by codyoss** [comment]
Thanks for the report, I will look into this soon.

**Comment by codyoss** [comment]
Sorry for the slow response. The imports flag is meant to help generate mocks and not rename imports. It should only be used in cases where mockgen can not detect that a required import is need. From the docs:

```
A list of explicit imports that should be used in the resulting
    source code, specified as a comma-separated list of elements of the form
    `foo=bar/baz`, where `bar/baz` is the package being imported and `foo` is
    the identifier to use for the package in the generated source code.
```

Are you looking for the package flag?

```
`-package`: The package to use for the resulting mock class
    source code. If you don't set this, the package name is `mock_` concatenated
    with the package of the input file.
```

**Comment by piersy** [comment]
Hi @codyoss thanks for getting back to me.

My initial issue was that my generated mock was importing a package with the same package name as the mock.

E.G:
```go
package foo

import (
	gomock "github.com/golang/mock/gomock"
	foo "github.com/blabla/foo"
...
```

I see now that we are using the `-package` flag and so could simply not use the `-package` flag. I would of course have to update all uses of the mock to use the new package name.

I'm wondering how does gomock handle the import of two same named packages?

E.G:
```
github.com/blabla/foo
github.com/lala/foo
```

**Comment by codyoss** [comment]
It will append an increasing number to the name of the second import

```
import (
   io github.com/blabla/foo
   io0 github.com/lala/foo
)
```
