### ISSUE TITLE
mockgen failing with error 'Loading input failed: Source directory is outside GOPATH'

### ISSUE THREAD

**Issue by pranay-1995** [golang/mock#437]
I am trying mock file using mockgen. I installed mockgen with 'go get github.com/golang/mock/mockgen'.

However, mockgen is failing with error,
C:\Users\deshmukh7\go\bin>mockgen.exe -source=C:\Users\deshmukh7\go\src\environment.go
**2020/05/27 14:28:53 Loading input failed: Source directory is outside GOPATH**

Note that environment.go is in GOPATH/src.

C:\Users\deshmukh7\go\bin>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\deshmukh7\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\deshmukh7\go;
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\DESHMU~1\AppData\Local\Temp\go-build240301262=/tmp/go-build -gno-record-gcc-switches

**Comment by codyoss** [comment]
Can you please tell me:
- What version of mockgen are you using?(`mockgen -version`)
- What version of Go are you using?
- Are you using GOPATH, or the new modules workflow?

**Comment by pranay-1995** [comment]
> mockgen -version
2020/06/03 19:08:48 No version information found. Make sure to use GO111MODULE=on when running 'go get' in order to use specific version of the binary.

> go version
go version go1.14.4 windows/amd64

I am using GOPATH

**Comment by codyoss** [comment]
Does running the following fix the issue for you:
```
GO111MODULE=on mockgen.exe -source=C:\Users\deshmukh7\go\src\environment.go
2020/05/27 14:28:53 Loading input failed: Source directory is outside GOPATH
```

**Comment by savishy** [comment]
I'm encountering the same error, and adding `GO111MODULE=on` does not fix it.

**Comment by codyoss** [comment]
@savishy Is `/Users/USERNAME/SOME/DIR/mock` in `GOPATH`?

**Comment by codyoss** [comment]
Closing due to lack of response. If you are still having issues and can provide us with more details we can re-open.

**Comment by learner-raghav** [comment]
Hello!

I am having the exact same issues.
My GOPATH is = "/home/raramuri/go"
My Code is present in = "/home/raramuri/go/Onion_Architecture/store"

I am trying to generate mock for a file inside the store directory. 
Please help me understand what i am doing wrong .

**Comment by codyoss** [comment]
@learner-raghav Would you please open a new issue with a minimal reproducer?

**Comment by Yoge-Code** [comment]
run `go mod init` that solve my problem
