### ISSUE TITLE
not  support multi-path gopath  

### ISSUE THREAD

**Issue by wencan** [golang/mock#438]
My team has not switched to go module.
The value of my gopath contains multiple paths, like this: 
```
/Users/user/gohome:/Users/user/project1:/Users/user/project2
```
I get an error: "Source directory is outside GOPATH", When I execute mockgen under the project.
I have submitted a new Pull Request #435  to solve this problem.

**Comment by codyoss** [comment]
Accepted, thank you!

**Comment by asv** [comment]
this patch breaks Bazel based environments.

**Comment by codyoss** [comment]
@asv Please open a detailed issue with a reproducer.
