### ISSUE TITLE
Opportunity write interfaces in different packages to single file

### ISSUE THREAD

**Issue by kozmod** [golang/mock#441]
*Requested feature* A clear description of the desired feature and an example of
how it would be used.
It will be nice to save different interface to single file , declaring import paths and interfaces consistently:
```
mockgen -destination ./mock_interfacs_test.go  -package=ex github.com/example/mock TestInterface,TestInterface3 github.com/example/mock/int2 TestInterface2
```
interfaces in `ex ` package
```
package ex

type TestInterface interface {
	EXECUTE(string) int
}

type TestInterface3 interface {
	EXECUTE_3(string) int
}

```
interfaces in `int2 ` package
```
package int2

type TestInterface2 interface {
	EXECUTE_2(string) int
}

```
result 
```
├── int2
│   └── test_int_2.go
├── test_int.go
├── mock_interfacs_test.go
└── tools.go

```

*Why the feature is needed* 
It will be convenient store all generated mocks in single file - generalization  abstraction for a single test package in  one file.
pr:[#442](https://github.com/golang/mock/pull/442)

**Comment by codyoss** [comment]
Thanks for the feature request. After some thought I don't think we will be moving forward with this request at this time. I would like to keep the CLI as simple as possible. For cases where you have multiple mocks in different packages I suggest the use of `//go:generate ...` in different package files. The you can run `go generate ./...` to generate all the mocks for your project.

**Comment by kozmod** [comment]
👍🏻
