### ISSUE TITLE
Explicit Never

### ISSUE THREAD

**Issue by decanus** [golang/mock#448]
*Requested feature* Add an explicit `never` call expectation.

*Why the feature is needed* It is nice to be able to be explicit about such things.

*(Optional) Proposed solution* - https://github.com/golang/mock/pull/444

**Comment by codyoss** [comment]
This is syntax sugar for `Times(0)`, right? I think is seems equally as explicit.

**Comment by decanus** [comment]
Yeah it essentially is @codyoss

**Comment by codyoss** [comment]
As there is already a way to do this today that seems explicit, as noted above, we will not be adding this feature at this time.
