### ISSUE TITLE
Concurrent calls with different arguments lead to failing test

### ISSUE THREAD

**Issue by JVecsei** [golang/mock#449]
**Actual behavior** 

```java
mockDoer.EXPECT().DoSomething(1, "first this")
mockDoer.EXPECT().DoSomething(2, "then that")
```
After mocking like this, I am calling a method, that starts multiple workers.
Problem is now: If the method is called first with the "2", this test fails. I was expecting the order not to matter, since there are dedicated functions for it (`inOrder`, `After`). Somehow this though fails 25% the time telling me first that the method was expected to be called with "1, first this" but it was called with "2, then that", and the other way around. 

Is there anything else I can do if the order of call does not matter, but I want the method to be called twice with differen parameters?

As soon as I discard the parameters everything works 😞 

```java
mockDoer.EXPECT().DoSomething(gomock.Any(), gomock.Any())
```

**Expected behavior**

The order of execution should not matter.

**Additional Information**

-   gomock version: github.com/golang/mock v1.4.3

**Comment by sinujohn91** [comment]
Facing the same issue. Were you able to solve this?
