### ISSUE TITLE
Mockgen is running an error while updating to latest version

### ISSUE THREAD

**Issue by znjuko** [golang/mock#451]
**Actual behavior** I was using mockgen v1.0.0 and running `mockgen -source=foo.go` was successful. But know i am getting too many errors like : 
`snap/go/5830/src/runtime/panic.go:830:20: invalid operation: shift count i (variable of type int) must be unsigned integer
/snap/go/5830/src/runtime/panic.go:852:34: invalid operation: shift count i (variable of type int) must be unsigned integer
/snap/go/5830/src/runtime/panic.go:800:26: invalid operation: shift count shift (variable of type int) must be unsigned integer
/snap/go/5830/src/runtime/panic.go:802:31: invalid operation: shift count shift (variable of type int) must be unsigned integer
/snap/go/5830/src/runtime/mpallocbits.go:170:20: invalid operation: shift count j (variable of type int) must be unsigned integer
/snap/go/5830/src/unicode/utf8/utf8.go:29:8: expected ';', found b00000000
/snap/go/5830/src/unicode/utf8/utf8.go:65:1: expected 'IDENT', found 'var'
/snap/go/5830/src/unicode/utf8/utf8.go:88:1: expected 'IDENT', found 'type'
/snap/go/5830/src/unicode/utf8/utf8.go:88:1: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:88:18: expected ';', found 'struct'
/snap/go/5830/src/unicode/utf8/utf8.go:94:1: expected 'IDENT', found 'var'
/snap/go/5830/src/unicode/utf8/utf8.go:104:1: expected 'IDENT', found 'func'
/snap/go/5830/src/unicode/utf8/utf8.go:104:1: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:104:14: expected ';', found '('
/snap/go/5830/src/unicode/utf8/utf8.go:106:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:106:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:106:7: expected ';', found '=='
/snap/go/5830/src/unicode/utf8/utf8.go:107:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:107:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:108:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:109:4: expected ';', found ':='
/snap/go/5830/src/unicode/utf8/utf8.go:110:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:110:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:110:7: expected ';', found '>='
/snap/go/5830/src/unicode/utf8/utf8.go:111:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:111:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:112:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:114:9: expected ';', found ':='
/snap/go/5830/src/unicode/utf8/utf8.go:115:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:115:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:115:7: expected ';', found '>'
/snap/go/5830/src/unicode/utf8/utf8.go:116:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:116:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:117:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:117:4: expected ';', found 'else'
/snap/go/5830/src/unicode/utf8/utf8.go:117:9: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:117:9: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:117:14: expected ';', found '>'
/snap/go/5830/src/unicode/utf8/utf8.go:118:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:118:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:119:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:120:2: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:120:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:121:1: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:124:1: expected 'IDENT', found 'func'
/snap/go/5830/src/unicode/utf8/utf8.go:124:1: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:124:22: expected ';', found '('
/snap/go/5830/src/unicode/utf8/utf8.go:126:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:126:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:126:7: expected ';', found '=='
/snap/go/5830/src/unicode/utf8/utf8.go:127:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:127:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:128:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:129:4: expected ';', found ':='
/snap/go/5830/src/unicode/utf8/utf8.go:130:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:130:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:130:7: expected ';', found '>='
/snap/go/5830/src/unicode/utf8/utf8.go:131:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:131:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:132:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:134:9: expected ';', found ':='
/snap/go/5830/src/unicode/utf8/utf8.go:135:2: expected 'IDENT', found 'if'
/snap/go/5830/src/unicode/utf8/utf8.go:135:2: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:135:7: expected ';', found '>'
/snap/go/5830/src/unicode/utf8/utf8.go:136:3: expected 'IDENT', found 'return'
/snap/go/5830/src/unicode/utf8/utf8.go:136:3: missing constant value
/snap/go/5830/src/unicode/utf8/utf8.go:137:2: expected 'IDENT', found '}'
/snap/go/5830/src/unicode/utf8/utf8.go:137:4: expected ';', found 'else'
/snap/go/5830/src/unicode/utf8/utf8.go:137:9: expected 'IDENT', found 'if'
`

**Additional Information**

-   gomock mode - source
-   gomock version - latest (1.4.3)
-   golang version - go1.14.4
-   golang env - 

> GO111MODULE=""
> GOARCH="amd64"
> GOBIN="/home/znjuko/go/bin"
> GOCACHE="/home/znjuko/.cache/go-build"
> GOENV="/home/znjuko/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/znjuko/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/snap/go/5830"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/snap/go/5830/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD="/home/znjuko/go/deploy-service/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build991627750=/tmp/go-build -gno-record-gcc-switches"
>

**Comment by StuartScott5** [comment]
I'm getting the same issue. Was there a solution to this one please?

**Comment by kevinmachstudio** [comment]
@znjuko how did you fix this issue?

**Comment by hitzam** [comment]
@znjuko how to resolve it? i'm facing the same issue.

**Comment by znjuko** [comment]
@hitzam sup!
i've just updated to newest version of golang via reinstalling it :)
