### ISSUE TITLE
Add the ability to add latency to mocks

### ISSUE THREAD

**Issue by bradwilzon** [golang/mock#454]
I have some cases where time comes into play. A recent example:

```golang
// short-circuit early
if time.Now().After(deadline) {
    return errors.New("already too late")
}

// dep calls ... 

// short-circuit for product safety
if time.Now().After(deadline) {
    return errors.New("not enough time left")
}
```

I would like to be able to simulate latency during my mocked dep calls to facilitate testing this kind of use case.

### Workaround
Manually mock a dep and use `time.Sleep(x)` in the implementation. 

### Request
It would be nice to have something like `dep.EXPECT().Method().Latency(x).Return(nil)` where the recorder just sleeps for the duration I provide.

**Comment by cvgw** [comment]
Apologies if I'm misunderstanding, but couldn't this currently be achieved using a `Do` or `DoAndReturn` call? 

IE

```
dep.EXPECT().Method().DoAndReturn(
    func() foo {
        time.Sleep(x)
        return foo
    })
```

**Comment by bradwilzon** [comment]
> Apologies if I'm misunderstanding, but couldn't this currently be achieved using a `Do` or `DoAndReturn` call?

Yes, you may be able to. I struggled to find good examples of how to use DoAndReturn() because it's not used very often. This should be considered a convenience method.

In https://github.com/golang/mock/pull/455 I instead addAction().

**Comment by codyoss** [comment]
As there is a way to do this already today I would prefer to not expand the API right now. Will will add some docs that better show how to do something like this. Thanks.
