### ISSUE TITLE
resolve pointer based types w/ reflect

### ISSUE THREAD

**Issue by adone** [golang/mock#46]
Hi! I know that there is already existed PR  #39 for this problem. But I have different simple solution #45.

**Comment by codyoss** [comment]
Hey @adone, I realize this is an old issue, but I was wondering if you could provide a small example of what the issue is here and what you expect. If this is still an issue, I would like to get it resolved.

**Comment by codyoss** [comment]
Closing due to lack of response. Please reopen if later if you are interested in this again.
