### ISSUE TITLE
How to combine the usage of GotFormatter and WantFormatter

### ISSUE THREAD

**Issue by fanadol** [golang/mock#462]
Hi, i am having struggle to understand how to print struct in `Want` and `Got` when test fail. In README, i read about `GotFormatter` and `WantFormatter`, i try that, and yes it works for individual. My question is how i combine both in `EXPECT` function ?

lets say i have
```
// msg is a struct
m.EXPECT().SendMessage(msg)
```

i could do
```
// or GotFormatter
gfmt := gomock.WantFormatter(...., gomock.Eq(msg))
m.EXPECT().SendMessage(gfmt)
```

But i cannot use both `WantFormatter` and `GotFormatter`.
I want to print `want` and `got` with the struct key (something like `%+v`). 

Thank you

**Comment by cvgw** [comment]
I found the docs to be quite confusing, I'll update them.

Here is an example of how to do both

Say you have `m.EXPECT().SendMessage(gomock.Eq("a"))`

```
          eq := gomock.WantFormatter(
                  gomock.StringerFunc(func() string { return "is equal to foobar" }),
                  gomock.Eq("a"),
          )

          eq = gomock.GotFormatterAdapter(
                  gomock.GotFormatterFunc(
                          func(i interface{}) string {
                                  return fmt.Sprintf("%02d", i)
                          }),
                  eq,
          )

          m.EXPECT().SendMessage(eq)
```

**Comment by fanadol** [comment]
Hi @cvgw , i've tried that and it works. 

Yes the docs quite confusing, but thanks to your explanation now i understand.

Thanks
