### ISSUE TITLE
Issue white generating mocks

### ISSUE THREAD

**Issue by dennypenta** [golang/mock#468]
*Requested feature*
While I'm generating mocks I'm getting the issue if file has imports with the same ending, for example:
``` go
import "log"
import "google/log"
```
but there is a different package name, google/log actually has the package name as glog and it compiles well.

*Why the feature is needed* 
It doesn't obviously that I have to add the alias to each import

**Comment by codyoss** [comment]
I just tested the following and it worked fine.

```go
package gm468

//go:generate mockgen -source=main.go -destination=main_mock.go -package=gm468

import (
	"log"
	"os"

	klog "github.com/go-kit/kit/log"
)

type Bar interface {
	Baz(klog.Logger, log.Logger) string
}

func Foo() {
	log.Println("hello", "world")
	l := klog.NewLogfmtLogger(os.Stdout)
	l.Log("hello", "world")
}
```

I ran `go generate`.

Imports from the mock:

```go
import (
	log0 "log"
	reflect "reflect"

	log "github.com/go-kit/kit/log"
	gomock "github.com/golang/mock/gomock"
)
```

Closing for now, if you can provide a small example I might be able to help more.
