### ISSUE TITLE
Expect any method not called

### ISSUE THREAD

**Issue by Russiancold** [golang/mock#484]
Hi! Is there a way to verify that no methods of mock were called?
Smth like: `fooMock.EXPECT().Any().Times(0)`

**Comment by codyoss** [comment]
Hey thanks for the question. If you have an interface that has two methods `Foo` and `Bar` you would need to have explicit expectation for each of them:

```go
mock.EXPECT().Foo().Times(0)
mock.EXPECT().Bar().Times(0)
```

**Comment by Russiancold** [comment]
Can I implement this feature somehow? I believe it could be useful.

**Comment by codyoss** [comment]
As there is already a way to do this today I would lean towards not adding another way. This would require an additional method to be added to every generated MockRecorder.
