### ISSUE TITLE
[question] Not able to use generated NewMock with map in a struct, but normally working in struct without map

### ISSUE THREAD

**Issue by HelloKuldeep** [golang/mock#485]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Nothing as such

### What operating system and processor architecture are you using (`go env`)?
GOOS="darwin"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOPATH="/Users/zo/go"
GOPRIVATE="github.com/Z/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.6/libexec"

</pre></details>

### What did you do?
Trying to use generated mock into a struct that has used the interface () in a map

for the given code:
- interface & struct used

```
        //  mock generated for this interface
	type TplExternalService interface {
		// some functions
	}

	type TplExternalServiceFactory struct {
		ServiceMap map[enum.LP]TplExternalService
	}
```

- test file using

```
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mockTpl := mocklogs.NewMockTplExternalService(ctrl)

	tplExternalServiceFac := &TplExternalServiceFactory{
		ServiceMap: map[enum.LP]mockTpl,        // getting error on this line
	}

```

### What did you expect to see?
Also if trying struct having directly the given interface then in test file error gets resolve. That is:
Changing struct to -
```
	type TplExternalServiceFactory struct {
		ServiceMap TplExternalService
	}
```

Changing test file to -
```
	tplExternalServiceFac := &TplExternalServiceFactory{
		ServiceMap: mockTpl,       // now this works fine
	}
```

### What did you see instead?
Cannot use 'map[enum.LP]mockTpl' (type map[enum.LP]mockTpl) as type map[enum.LP]TplExternalService
mockTpl is not a type

**Comment by codyoss** [comment]
Hey,

I am having a hard time understanding the exact problem you are having here. Could you please provide a simple gist showing a minimal reproducer for this?

**Comment by zkuldeep** [comment]
Hi @codyoss 

So, whenever I'm using my mocked interface NewMockXYZ (i.e. here `mockTpl`) in substituting it in struct that has a field of type map[_something_]**That_Interface** it showing error (as mentioned above) but when its used against struct with field of type **That_Interface**, its acceptable which is okay, as per its required behaviour, but I need the case when used with `map`.

**Comment by HelloKuldeep** [comment]
Hi @codyoss 

So, whenever I'm using my mocked interface NewMockXYZ (i.e. here `mockTpl`) in substituting it in struct that has a field of type map[_something_]**That_Interface** it showing error (as mentioned above) but when its used against struct with field of type **That_Interface**, its acceptable which is okay, as per its required behaviour, but I need the case when used with `map`.

**Comment by codyoss** [comment]
I think I see now. It looks like you are incorrectly instantiating your map by trying to change its type. Something like the following will work:

```go
tplExternalServiceFac := &TplExternalServiceFactory{
		ServiceMap: map[enum.LP] TplExternalService{},
	}
tplExternalServiceFac.ServiceMap["some enum of yours"] = mockTpl
```

**Comment by HelloKuldeep** [comment]
Thanks I understood this instantiation, but can't we keep this `ServiceMap` generic of any `enum.LP`, something like this - 
```
tplExternalServiceFac := &TplExternalServiceFactory{
		ServiceMap: map[enum.LP]mockTpl,
}
```
I'm asking this since `ServiceMap` is instantiated with mocked interface & during test-run my `enum.LP` has to be decided.
Anyways, thanks for this, I'm managing this this to get before hand.

**Comment by codyoss** [comment]
Here it is declared the contract for type uses an interface:

```go
type TplExternalServiceFactory struct {
		ServiceMap map[enum.LP]TplExternalService
	}
```

 At runtime you can put mock into the map that satisfies the interface, but you can't change the type.

```go
tplExternalServiceFac := &TplExternalServiceFactory{
		ServiceMap: map[enum.LP]mockTpl,
}
```
 The above is not valid Go code. Here is an example, not using gomock, that shows this. https://play.golang.org/p/1g8VozrhsJm
