### ISSUE TITLE
Error matcher

### ISSUE THREAD

**Issue by ymohl-cl** [golang/mock#487]
Hello

I would like to be able to test equality on an error but i could not do it with the Eq Matcher or other stuff.
If the error interface is implemented by a custom error, Eq return a Failure case.

```
// in my code (c is a gin gonic context to information)
if err = c.BindJSON(&order); err != nil {
    customLogger.Error(err)
}

// from the units tests:
mockLogger.EXPECT().Error(gomock.Eq(errors.New("error return by Bind in my failure case")))
```

So Eq matcher return fail because BindJson implement error from the primitive type  *json.SyntaxError (verifiable by `fmt.Printf("error source: %s\n", reflect.TypeOf(err).String())`) and i compare it with an implementation error from the package errors.

*Why the feature is needed*
I would like check my error content without have a knowledge of primitive type use by dependencies.
error type is a native interface and i think that we should be able test it by the interface and not by the primitive type or other stuff.

*Proposed solution:
If you are ok with that, i send you a PR.

I hope i haven't missed anything in using Gomock. thank you for your work

**Comment by codyoss** [comment]
Matcher is a public interface so anyone can define their own matchers in their codebases. For this type of Matcher I would recommend defining it in your codebase. Different people might have different ideas of what an equal error is. For instance some people might want errors to be equal if one error [Is](https://pkg.go.dev/errors#Is) another error.

Although in some cases it might make sense to rely upon a string match for error testing, it can also lead to fragile tests. For instance if you rely on package `foo` and you asset an error message is equal to a certain string that test may latter fail if you upgrade a dependency and they added more detail to their error message.
