### ISSUE TITLE
Installing mockgen does not get added to path

### ISSUE THREAD

**Issue by pickfire** [golang/mock#490]
**Actual behavior** Mockgen was added in `~/src/go/bin/mockgen` by installing it with `GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4`, but no warnings were given that `~/src/go/bin` is not part of `PATH` environment variables.

**Expected behavior** A clear and concise warning should be given to users when installing.

**To Reproduce** Steps to reproduce the behavior

1.  `GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4`

**Additional Information**

-   gomock mode (reflect or source):
-   gomock version or git ref: v1.4.4
-   golang version: go version go1.15.2 linux/amd64

**Triage Notes for the Maintainers**

**Comment by codyoss** [comment]
Hey,

All go binaries are by default installed to $GOPATH/bin. It is common practice to add this location to your PATH. It is the responsibility of the user to do so. 

There is no warning we could provide in the tooling, but we could add a note to our README. Feel free to open a PR if you are willing.

**Comment by montogeek** [comment]
> There is no warning we could provide in the tooling,

Why?
