### ISSUE TITLE
Feature Request: Assert mocks are not called earlier than expected

### ISSUE THREAD

**Issue by ggarek** [golang/mock#492]
*Requested feature*

Make it possible to assert that mocks were not yet called.

*Why the feature is needed*

It could be the object under test should call dependencies only in response to
external interaction.

Say, you create the object you want to test and inject mocked dependencies. Then
you want to assert that those dependencies were called only after you interacted
with the object. (Put it in other words, the dependencies were not called before
you interacted with the object)

*Proposed solution*

This is a way how one can get this functionality without modifying the library,

<details>
<summary>A Barrier utility to assert that mocks are not called earlier than they should</summary>

```go
//
//  Demo test case
//

type MyDependency interface {
	DoSomething()
}

type MyConsumer struct {
	dep MyDependency
}

func NewMyConsumer(dep MyDependency) *MyConsumer {
	// Ooops, we shouldn't be calling our dependency in the constructor (e.g. by design)
	dep.DoSomething()
	return &MyConsumer{dep: dep}
}
func (c *MyConsumer) CallDep() {
	c.dep.DoSomething()
}

// This test fails because the implementation calls the dependency earlier than expected.
func Test_DetectsTheDependencyIsCalledEarlierThanItShould(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	d := NewMockMyDependency(ctrl)
	c := NewMyConsumer(d)

	barrier := NewMockBarrier(ctrl)

	// This asserts that MyDependency.DoSomething shouldn't be called before the
	// barrier is activated.
	gomock.InOrder(
		barrier.EXPECT(),
		d.EXPECT().DoSomething(),
	)

	// Activate the barrier first
	barrier.Call()
	// Call the consumer, that will call the dependency
	c.CallDep()
}

// This test passes failing to detect the unwanted call.
func Test_PassesAlthoughThereIsUnwantedCallInConstructor(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	d := NewMockMyDependency(ctrl)
	c := NewMyConsumer(d)

	// NOTE: In this example we could say that the dependency should be called
	// only once, but it is not reliable, because the implementation can have a
	// single call just in a wrong place.
	d.EXPECT().DoSomething()
	c.CallDep()
}

// MockBarrier is used to assert that mocks are called only after they are expected
// to be called.  That is after a certain moment in time that is marked with
// MockBarrier.EXPECT() call.
//
// For example, if you want assert that mockA.Call wasn't called before you
// expect you could write the following,
//
//  barrier := NewMockBarrier(ctrl)
//  gomock.InOrder(
//		barrier.EXPECT(),
//		mockA.EXPECT().Call(),
// 	)
//
//	If you comment the barrier.Call or move it after the mockA.Call() the test will fail.
//  barrier.Call()
//  mockA.Call()
//
type MockBarrier struct {
	ctrl *gomock.Controller
}

func NewMockBarrier(ctrl *gomock.Controller) *MockBarrier {
	return &MockBarrier{ctrl: ctrl}
}

func (b *MockBarrier) EXPECT() *gomock.Call {
	b.ctrl.T.Helper()
	return b.ctrl.RecordCallWithMethodType(b, "Call", reflect.TypeOf((*MockBarrier)(nil).Call))
}

func (b *MockBarrier) Call() {
	b.ctrl.T.Helper()
	b.ctrl.Call(b, "Call")
}
```

</details>

**Comment by cvgw** [comment]
I'm having some trouble understanding the specific problem this is trying to solve.

In your example test
```
// This test passes failing to detect the unwanted call.
func Test_PassesAlthoughThereIsUnwantedCallInConstructor(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	d := NewMockMyDependency(ctrl)
	c := NewMyConsumer(d)

	// NOTE: In this example we could say that the dependency should be called
	// only once, but it is not reliable, because the implementation can have a
	// single call just in a wrong place.
	d.EXPECT().DoSomething()
	c.CallDep()
}
```

I don't understand why it is not sufficient to specify the expected number of calls with `Times`. Whether the error case is 0+1 or N+M shouldn't matter IIUC.

**Comment by ggarek** [comment]
The example is a bit confusing indeed.  It should have had only one call to "dep.DoSomething()", not two.  

If there is only one call, then you may want to assert that it happens in the CallDep method, but not, for example, in the constructor.  _(This requirement comes from your design, say, you want to separate creation from initialization for some reason.)_

To check this behavior I need to assert "did the call happen after the test invoked c.CallDep()".  Assertion of a kind "did the call happen at all" doesn't satisfy the requirements, because it will pass if the call in question happens in constructor, rather than in CallDep method.

AFAIU, the library offers only "did the call happen at all" type of assertions.

p.s.: If it is still not clear, I think it is OK to close the issue.  I am not sure that my requirement is something other people may need.

**Comment by codyoss** [comment]
Closing this issue for now. Like cvgw I am a little confused what is being asked here. If you can provide more info and a modified example feel free to reopen.
