### ISSUE TITLE
mockgen generates duplicate implementation for overlapping interfaces in source mode

### ISSUE THREAD

**Issue by marten-seemann** [golang/mock#497]
**Actual behavior** 
Since Go 1.14 embedded interfaces can have overlapping methods, as the `io.Closer` in the following example:

```go
type readCloser interface {
	io.Reader
	io.Closer
}

type writeCloser interface {
	io.Writer
	io.Closer
}

type ReadWriteCloser interface {
	readCloser
	writeCloser
}
```

When generating a mock for `ReadWriteCloser`, the mock implementation will declare `Close() error` twice. The mock therefore fails to compile: `(*MockReadWriteCloser).Close redeclared in this block`

**Expected behavior**
The overlapping method should only be implemented once.

**To Reproduce** Steps to reproduce the behavior

`mockgen -source=xxx.go`

**Additional Information**

-   gomock mode (reflect or source): reflect
-   gomock version or git ref: v1.4.4
-   golang version: 1.15.3

**Comment by codyoss** [comment]
Thanks for the report, I will take a look at your PR today!
