### ISSUE TITLE
inconsistent order of methods on the mock interface between source and reflect mode

### ISSUE THREAD

**Issue by marten-seemann** [golang/mock#499]
**Actual behavior**
Consider the following interface:

```go
type WriteCloser interface {
	Write()
	Close()
}
```
In source mode `Write()` will come before `Close()`. In reflect mode, `Close()` will come before `Write()`.

While the Go compiler doesn't care about the order, it would be nice if the order was consistent between the two modes (imagine switching from source to reflect mode in a project. It would be nice if you wouldn't have to commit a large batch of changes to the mock files in your VCS).

**Expected behavior** 

The order should be consistent. Alphabetically ordered, for example.

**To Reproduce** Steps to reproduce the behavior

see example

**Additional Information**

-   gomock mode (reflect or source): both
-   gomock version or git ref: 1.4.4
-   golang version: 1.15.3

**Comment by codyoss** [comment]
Seems reasonable, thanks for the issue.
