### ISSUE TITLE
I agree that removing write permissions for 'Authenticated Users' from C:\Go\bin shouldn't break anything. For what its worth, I looked at a few other languages to see what they do, and it looks like python 2.7 and Ruby both add folders writable by this group to the system path. Python 3 and Haskell do not, by virtue of installing into subdirectories of C:\Program Files\ when installed for all users, from which they inherit secure permissions.

### ISSUE THREAD

**Issue by kja-jaj** [golang/mock#503]
I agree that removing write permissions for 'Authenticated Users' from C:\Go\bin shouldn't break anything. For what its worth, I looked at a few other languages to see what they do, and it looks like python 2.7 and Ruby both add folders writable by this group to the system path. Python 3 and Haskell do not, by virtue of installing into subdirectories of C:\Program Files\ when installed for all users, from which they inherit secure permissions.

_Originally posted by @menocu in https://github.com/golang/go/issues/42070#issuecomment-722617184_

**Comment by codyoss** [comment]
Was this issue meant to be opened here? I am not sure what is being asked. Closing for now, but feel free to reopen and update.
