### ISSUE TITLE
1.5.0 release

### ISSUE THREAD

**Issue by jameshalsall** [golang/mock#516]
Apologies if this is not the right approach for this kind of "issue", but I noticed that the 1.5.0 release is waiting on https://github.com/golang/mock/issues/262 (or at least it's in the 1.5.0 milestone), and it has been about 6-7 months since the last release of this library. 

I wonder, is it possible to make a release sooner and defer the above issue to 1.6.0?

**Comment by codyoss** [comment]
Sorry for the delay, but here it is! https://github.com/golang/mock/releases/tag/v1.5.0
