### ISSUE TITLE
Loading input failed: loading package failed

### ISSUE THREAD

**Issue by guoshengcc** [golang/mock#517]
I am use This command `mockgen -source=gomockdemo.go` get a error msg:`Loading input failed: loading package failed`

Then,In same env , use This comand `mockgen -source gomockdemo.go`,It work right. I am delete the '='

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version or git ref:v1.4.4
-   golang version: 1.15.6

**Triage Notes for the Maintainers**

**Comment by codyoss** [comment]
Can you please provide a code snippet. I am unable to reproduce this currently.

**Comment by guoshengcc** [comment]
Hi, this is [my code](https://github.com/guoshengcc/gomockUnitTest).
I tried again and still got the same error. 
In the readme file in my project, I provided detailed information, hoping to provide valid content

**Comment by codyoss** [comment]
I tried running your exact project on windows and macos and was unable to reproduce. This package makes use of Go's flag package so it should be handling both forms just fine. My best guess is it is something related to your shell. Do you use anything non-standard? Do you have problems with other Go programs that use the flag package?

**Comment by codyoss** [comment]
Closing due to lack of response. Please feel free to update if there is more to share.
