### ISSUE TITLE
how to mockgen embedded interface

### ISSUE THREAD

**Issue by ethantsien** [golang/mock#521]
File foo.go

```golang
type Foo interface {
    Bar
}
```

File bar.go

```golang
type Bar interface {
    Open()
    Write()
}
```

How to mockgen the file foo.go?

**Comment by codyoss** [comment]
Hey,

You can use reflect mode to do this easily as it will load the whole package(assumes module example.com/gm521 and code in package gm521): 

`mockgen -destination=foo_mock_test.go -package=gm521 example.com/gm521 Foo`
