### ISSUE TITLE
documentation needs a concrete "mockgen -import" example

### ISSUE THREAD

**Issue by csmith0651** [golang/mock#53]
I have a interface with an embedded http.ResponseWriter interface. However mockgen fails and there is no concrete example how how to solve this. I _believe_ I'm supposed to use the -imports flag but without a concrete example it is proving difficult to track down.  I debugged the mockgen code trying to track this down but ran out of time. A concrete example of this in the documentation would at least show me that it is not the right direction. Apologies if this should be attached to a subdirectory.

**Comment by sidorovis** [comment]
mockgen -source=yourfile.go -destination=packageNametest/mock_youfile.go -package=packageName -imports =github.com/<yourname>/<project>/<path>/packageName

**Comment by zhaoguojie2010** [comment]
> mockgen -source=yourfile.go -package=packageName -imports =github.com/yourname/project/path/packageName -destination=packageNametest/mock_youfile.go

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.parseFile(0x7ffeefbffb11, 0x14, 0x11376a2, 0xc00009dee0, 0x130e73e)
	/Users/zhaoguojie/go/src/github.com/golang/mock/mockgen/parse.go:83 +0xaf2
main.main()
	/Users/zhaoguojie/go/src/github.com/golang/mock/mockgen/mockgen.go:65 +0x9f8
```

any idea what went wrong?

**Comment by LucasDove** [comment]
ran into the same problem. 
macos, mojave 10.14.6
go version go1.12.5 darwin/amd64
golang/mock  v1.2.0

**Comment by kainobor** [comment]
If you'll read documentation, you'll see that: "-imports string (source mode) Comma-separated name=path pairs of explicit imports to use."
As result, you can use smth like this: 
`mockgen -source yourfile.go -package packageName -imports packageName=github.com/yourname/project/path/packageName -destination packageNametest/mock_youfile.go`

**Comment by codyoss** [comment]
I believe if we solve #156 in the correct way the example given in this issue should no longer be relevant. As well as most use cases that would require `-imports`. If you are currently using this flag can you please post short snippets of your use case this is helping you solve. I would like to make the use of this flag obsolete if possible in the future.

**Comment by piersy** [comment]
@codyoss I would like to use this flag to name an import whose name conflicts with the package that the mock exists in. Unfortunately the imports flag does not seem to work. See #436

**Comment by codyoss** [comment]
The reason this issue was originally opened for is no longer an issue. The imports flag is not required for this use case. If others have different examples that still don't work please report them as a new issue. Thanks.
