### ISSUE TITLE
Mockgen should create package names without under_scores

### ISSUE THREAD

**Issue by hongshaoyang** [golang/mock#537]
*Requested feature*

By default, Mockgen creates package names with `mock_` concatenated with the package of the input file.

This goes against guidelines, as documented in https://blog.golang.org/package-names:

> Good package names are short and clear. They are lower case, with no under_scores or mixedCaps. 

And in [Effective Go: MixedCaps](https://golang.org/doc/effective_go#mixed-caps): 

> [The] convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword names.

*(Optional) Proposed solution*

By default, Mockgen should create package names with **`mock`** concatenated with the package of the input file.

**Comment by KlausVii** [comment]
Since package names are not camelCased, adding words into them is bit finicky, hence usually trying to keep them one word etc. Using _ is already established in things like package_test, so I don't see any reason to change this. 

Besides `-package=` lets you set it whatever you like...

**Comment by codyoss** [comment]
I think the underscore notation is okay for mock. As @KlausVii points out you can change the default with a flag. I personally always manually specify the package flag. Every project is a little different and I don't think there is a good "one" solution here. Closing since this is overridable.
