### ISSUE TITLE
Built-in matcher that compares slices of arbitrary elements order

### ISSUE THREAD

**Issue by vvkh** [golang/mock#545]
# Requested feature
It would nice to have built-in matcher that compares slices and returns `true` if slices have same elements in arbitrary order.

# Why the feature is needed
Sometimes code we are testing produces slices with non-determined elements order. For example, when converting map to slice we may end up with many possible orders of elements.
```
s := make([]interface{}, 0, len(m))
for k, v := range m {
    s = append(s, v)
}
```
Some testing frameworks like testify include [special assert function](https://github.com/stretchr/testify/blob/6990a05d54c2287be8787a411d77815643347339/assert/assertions.go#L895) checking if two slices have same elements.

If we have a mock depending on arguments with non-determined elements order such as `s` then setting up expected calls for such mock can be quite inconvenient. We either have to use `Any()` matcher and skip validating this argument at all or implement custom matcher.  

# Proposed solution
Include built-in matcher like `InAnyOrder(s []interface{})` or `WithSameElements(s []interface{}` implementing checks similar to [assert.ElementsMatch](https://github.com/stretchr/testify/blob/6990a05d54c2287be8787a411d77815643347339/assert/assertions.go#L895)

P.S.
I will be happy to implement the matcher if we agree on this feature being useful.

**Comment by codyoss** [comment]
Hey, thanks for the feature request. I will let this issue sit for a little bit to see what others in the community think of the idea. I could see how a matcher like this could be useful.

**Comment by vvkh** [comment]
Hey @codyoss.  I've provided [draft implementation](https://github.com/golang/mock/pull/546) for requested issue. Could you please take a look?

**Comment by vvkh** [comment]
Implemented in https://github.com/golang/mock/pull/546
