### ISSUE TITLE
mockgen：Loading input failed: Source directory is outside GOPATH

### ISSUE THREAD

**Issue by pfx546746447** [golang/mock#549]
-   gomock mode (reflect or source): source
-   gomock version or git ref: v1.5
-   golang version: 1.16.2

**Comment by codyoss** [comment]
Can you please provide some more info to help debug:

1) A small code sample of what you are trying to mock.
2) The exact command you are using to generate the mock.
3) Where you are running that command in relation to the code?

Usually this error means you should just run mockgen from a different directory.

**Comment by pfx546746447** [comment]
today i'm on the company computer has this issue,but the computer at home is normal just now.
I will try to reinstall it on the company computer,thx

**Comment by codyoss** [comment]
Closing for now, feel free to reopen if it is still happening and you can provide more details.
