### ISSUE TITLE
Panic on array parsing if length is externally defined

### ISSUE THREAD

**Issue by jmaeso** [golang/mock#561]
**Actual behavior** 

generating code for the following interface makes the tool to panic. 

(Note: math constant used just for convenience. Can be any other package-defined constant, not a hardcoded value)
```go
type Fooer interface {
    Foo([math.MaxInt8]string)
}
```
Output: `panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.BasicLit`

**Expected behavior**

Generate a mocked struct with a method that takes a `[127]string{}` (or `[math.MaxInt8]string{}`) array

**To Reproduce** Steps to reproduce the behavior
Explained in the "Actual behaviour" section

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version or git ref: v1.5.0
-   golang version: go version go1.15.8 darwin/amd64

~~**Triage Notes for the Maintainers**~~

**Comment by codyoss** [comment]
Thanks for the report. It looks like more work needs to be done onto the changes that were made in #520. I think those changes assume that the const is defined locally. I would be willing to accept a PR for this issue.
