### ISSUE TITLE
How about to add an official mockgen docker image?

### ISSUE THREAD

**Issue by kulti** [golang/mock#563]
*Requested feature*
I'd like to generate mocks using docker image like this `docker run -v $(PWD):/app golang/mock mockgen -destination=mock_db_test.go -package=app_test . UsersDB`.

*Why the feature is needed*
Different environments can have different versions of mockgen. It will be better to generate mocks via docker image.

*(Optional) Proposed solution*
This repo already uses goreleaser. So it should not be so hard to add docker image publishing.

**Comment by codyoss** [comment]
Hey thanks for the request. At this time I do not think that publishing a Docker image with just mockgen would provide enough value. If you have a CI system that is based on Docker I would recommend that it download one of the published binaries that we provide with our releases. [Example](https://github.com/golang/mock/releases/tag/v1.5.0).

**Comment by kulti** [comment]
Thank you for your suggestion. Code is generated by developers, not in CI. Configuring multiple environments with different OS and users' preferences is not a simple task :)

I understand your point. For me, the docker image with mockgen has enough value. We have our own docker registry. I write Dockerfile and use docker image locally.
