### ISSUE TITLE
Mockgen : Imports doesn't generate import line

### ISSUE THREAD

**Issue by marcelloh** [golang/mock#620]
When I add an import flag to the generate like this
-imports repository=github.com/company/framework/middleware/repository
I expect the line to be added as an import in the generated mock

**To Reproduce** Steps to reproduce the behavior

//go:generate mockgen -destination=./mocks/mock-repo.go -self_package=github.com/company/customer/vendor/github.com/company/framework/middleware/repository -package=mocks -source=../vendor/github.com/company/framework/middleware/repository/repository.go -imports repository=github.com/company/framework/middleware/repository

**Additional Information**

-   gomock mode : source
-   gomock version : 1.6.0
-   golang version: 1.17.7

**Triage Notes for the Maintainers**

**Comment by codyoss** [comment]
Hey, sorry for the slow rely, can yo please share some code to reproduce this?

**Comment by MarcelXia** [comment]
I'm sorry, I have to dig deep. 2 .5 months ago, that's like 2 human years :-(

**Comment by codyoss** [comment]
Without seeing an example this will be hard for me to reproduce. I am closing this for now but feel free to reopen if you can provide an example.

**Comment by junmaqiang** [comment]
## The following sentence is invalid
-imports repository=github.com/company/framework/middleware/repository
