### ISSUE TITLE
Source mode fails with embedded interfaces in the same package

### ISSUE THREAD

**Issue by joy717** [golang/mock#638]
this issue is the same with https://github.com/golang/mock/issues/178
the `sourceFile` and the `EmbededFile` are in the same package but are different files.

even use this command, still got an error:
```
mockgen -source test2.go -destination test2_mocks.go -package test -aux_files=github.com/anyuser/test=test1.go
```

I know there is another issue: https://github.com/golang/mock/issues/85
but #85 is two files in two packages.

gomock version: 1.6.0

**Comment by joy717** [comment]
It's worked great.
That's my fault.
I'm using go module. the package name in `-aux_files` was misconfigured

**Comment by Yuu177** [comment]
I have the same problem, how did you solve it?

**Comment by joy717** [comment]
It's worked great. It was the wrong package name that caused the problem.

**Comment by caiqiyong** [comment]
I get the same problem, how did you solve it? 

> h

hey, I got the same problem, the command below still not work, how did you solve the problem?  

`mockgen -source test2.go -destination test2_mocks.go -package test -aux_files=github.com/anyuser/test=test1.go`

what did you mean misconfigure package name?

**Comment by joy717** [comment]
> hey, I got the same problem, the command below still not work, how did you solve the problem?
> 
> `mockgen -source test2.go -destination test2_mocks.go -package test -aux_files=github.com/anyuser/test=test1.go`
> 
> what did you mean misconfigure package name?

I worte a wrong package name.



-aux_files $PACKAGE_NAME=$REAL_LOCATION_OF_FILE

the $REAL_LOCATION_OF_FILE is based on the path of `mocken xxxx` command executed.

for example:
if I executed `mockgen -source test2.go ...` in the location `github.com/anyuser/`,
-aux_files github.com/anyuser/test=../test1.go

but if I exected mockgen -source test2.go ...` in the location `github.com/anyuser/test/`,
then
-aux_files github.com/anyuser/test=test1.go
