### ISSUE TITLE
A non-fatal version of Finish() would be helpful for tabular tests

### ISSUE THREAD

**Issue by RJPercival** [golang/mock#64]
Currently, if `Finish()` is called and some expected calls did not occur, `t.Fatal()` is called, aborting the test. However, in the cast of tabular tests, it would be preferable if only `t.Error()` was called so that the other test cases could be run.

**Comment by pasztorpisti** [comment]
A possible (very good) workaround is creating separate subtests for the test cases in the `for` loop:

```go
func TestWoof(t *testing.T) {
	table := []struct {
		name string
	}{
		{"t1"},
		{"t2"},
		{"t3"},
	}
	for _, tc := range table {
		t.Run(tc.name, func(t *testing.T) {
			t.Fatal("err " + tc.name)
		})
	}
}
```

**Comment by RJPercival** [comment]
Indeed, subtests do solve this issue.
