### ISSUE TITLE
`running "mockgen": exec: "mockgen": executable file not found in $PATH`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [golang/mock#642]
I have this error on `go generate ./...` 

BUT

$ mockgen --version
v1.6.0

$ which mockgen
/home/vitaly/go/bin/mockgen

First line of the file from error:
`//go:generate mockgen -source=interface.go -destination=interface_mock.go -package=alarms`

In `go.mod` I have:
`github.com/golang/mock v1.6.0`

`go mod tidy` do nothing.

go 1.17.8

Gentoo Linux

**Comment by codyoss** [comment]
Sounds like you may need to add mockgen to your PATH. Please take a look at the note in the [installation instructions](https://github.com/golang/mock#installation). Hope that helps!

**Comment by vitaly-zdanevich** [comment]
In my PATH I already have `PATH=~/go/bin`

**Comment by codyoss** [comment]
@vitaly-zdanevich what happens when you type `which mockgen` in your terminal?

**Comment by vitaly-zdanevich** [comment]
As in original post:

`/home/vitaly/go/bin/mockgen`

**Comment by codyoss** [comment]
Does it work if you manually run the command from you terminal instead of go generate?

**Comment by vitaly-zdanevich** [comment]
Yes.

**Comment by vitaly-zdanevich** [comment]
SOLVED. Problem was that in PATH I had `~/go/bin` but must be `/home/vitaly/go/bin/`

**Comment by vitaly-zdanevich** [comment]
Did a related PR https://github.com/golang/mock/pull/644
