### ISSUE TITLE
Loading input failed: failed parsing source file mockdemo: open mockdemo: The system cannot find the file specified.

### ISSUE THREAD

**Issue by mrgAndysm** [golang/mock#652]
E:\mockdir> mockgen -source=mockdemo.go  
Loading input failed: failed parsing source file mockdemo: open mockdemo: The system cannot find the file specified.

**Comment by codyoss** [comment]
@mrgAndysm Can you please re-create this issue with our template and give more information how to reproduce. Thanks!

**Comment by melitadn** [comment]
hi
i also encounter the same issue
while trying to generate the mock file
project structure :
C:/.../parent/internal/handler/handler.go
C:/.../parent/internal/mocks/mock_handler.go

currently, I generate/execute from a command prompt on windows, and I am on the parent folder 
go mock version =
mockgen --version
v1.6.0

set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GO111MODULE=on
set GOARCH=amd64
set GOVERSION=go1.18
set GOOS=windows
set GOSUMDB=off
set GOEXE=.exe

i have try to add 	_ "github.com/golang/mock/mockgen/model"
and generated it using go mod vendor
i already have go mod file generated from go mod init as well 

mockgen -source=internal/handler/handler.go -destination=internal/mocks/mock_handler.go -package=mocks --build_flags=--mod=mod    
2022/07/19 16:35:41 Loading input failed: failed parsing source file internal/handler/handler: open internal/handler/handler: The system cannot find the path specified.
