### ISSUE TITLE
Expose the mockgen.generator type

### ISSUE THREAD

**Issue by wdullaer** [golang/mock#664]
It would be nice if the `generator` type in the mockgen package would be available publicly from its own package.

I am writing protoc plugin to add mocks to the generated code.
Since I know what the golang protoc plugin will produce, I can easily create a `model.Package` from the proto file.
Having only a single code generation step, executed by protoc greatly simplifies our build toolchain.

At the moment I have to copy the generator type and methods into my project, but it would be nice if I could just rely on the type from mockgen instead.

**Comment by codyoss** [comment]
At this time I don't think we will be exposing this. In the future we may consider a use case to use this code as a library but with current deps like calling out to go list this does not seem like a good idea to expose.
