### ISSUE TITLE
mockgen only create file and package, but not create interface and struct

### ISSUE THREAD

**Issue by cccccccccy** [golang/mock#670]
1.  ... mockgen --source model/dao/rpc/base.go --destination mock/mock_base.go
       only create:
// Code generated by MockGen. DO NOT EDIT.
// Source: model/dao/rpc/base.go

// Package mock_rpc is a generated GoMock package.
package mock_rpc

but when i use mockgen with other resp, it works correctly.

**Comment by codyoss** [comment]
Closing due to lack of response.
