### ISSUE TITLE
Maintenance status of mockgen

### ISSUE THREAD

**Issue by sodul** [golang/mock#672]
First I want to thank you for the work put in mockgen. This is a very valuable tool for Go based projects that practice unit testing.

We are getting concerned that the project is not getting enough support since there has not been any release in over a year now.

Go 1.18 and 1.19 have are here and there is no support for generics yet. The main branch has several fixes and improvements over the latest release and there are a few simple PRs still pending review.

If this is not the right place to start this conversation please point us to the right one.

@codyoss

**Comment by codyoss** [comment]
@sodul That is a great question. I have not been able to dedicate cycles to this project recently but would still like to get generics support out soon. I believe there are three open issues that are a part of the upcoming release milestone that should be fixed before a release is cut. I do know there is much anticipation for this release so I will try to find some time this week to see if we can push the needle closer. I will start with today cutting a rc release. I believe the solution on HEAD should cover many peoples use-cases so this will be a good way to get feedback and know if there are any other corner cases that have been missed. Thanks for reaching out!

**Comment by codyoss** [comment]
https://github.com/golang/mock/releases/tag/v1.7.0-rc.1
