### ISSUE TITLE
Hard to debug when a Do(fn) function no longer matches its mock signature

### ISSUE THREAD

**Issue by EtiennePerot** [golang/mock#71]
Situation: we had code like:
```go
type Foo interface {
  Bar(arg1, arg2 string)
  ...
}
```
and tests like:
```go
do := func(arg1, arg2 string) { ... }
// ... bunch of code ...
myBarMock.EXPECT().Bar(wantArg1, wantArg2).Do(do)
```

Then we added an argument to `Bar`:
```go
type Foo interface {
  Bar(arg1, arg2, arg3 string)
  ...
}
```
and updated the `EXPECT()`:
```go
do := func(arg1, arg2 string) { ... }
// ... bunch of code ...
myBarMock.EXPECT().Bar(wantArg1, wantArg2, wantArg3).Do(do)
```
... but forgot to update `do`. The result was "panic: reflect: Call with too many input arguments" with no strong indication that what was wrong was the `do` function, rather than some place where the third argument hadn't been added (e.g. missing `wantArg3`).
It would be nice if the message said something more obvious like "EXPECT.()Do() function doesn't match the mock signature".

**Comment by codyoss** [comment]
This seems reasonable. We are open to PRs :smile_cat:

**Comment by cvgw** [comment]
Reopening since the fix was reverted
