### ISSUE TITLE
Tag a semver-compatible release

### ISSUE THREAD

**Issue by akshayjshah** [golang/mock#72]
Is it possible for this project to tag a semver-compatible release? [Most of the Go community](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases), including the `dep` tool, is moving to this standard.

Without tagged releases, it's difficult for dependency management tools to work with this project.

**Comment by balshetzer** [comment]
done

**Comment by akshayjshah** [comment]
Thank you - especially grateful for the weekend work!

Also, my apologies - I didn't realize that I'd already filed an issue for this when I created #91.

**Comment by akshayjshah** [comment]
Err, #92.
