### ISSUE TITLE
mockgen needs a test suite

### ISSUE THREAD

**Issue by balshetzer** [golang/mock#81]
mockgen is currently being tested in an ad-hoc way. It needs a full and automated test suite to prevent breakages.

**Comment by pasztorpisti** [comment]
Do you have a concrete plan in mind?

The first thing that came to my mind was simply adding a travis-ci config that:
- Runs `go generate ./...` and checks if the results are different from the original file contents - this detects when someone forgets regenerating test mocks after modifying the logic
- Runs `go test ./...`

**Comment by balshetzer** [comment]
I don't have a concrete plan. I just realized I needed something after I broke mockgen with #78. I thought I tested it but clearly didn't test without the build flag.

Your plan generally sounds good. We also need to add some more test cases to cover the various mockgen features. These include using both reflect and source modes, the various command line flags, and setting up inputs that can exercise them.

**Comment by pasztorpisti** [comment]
Most bugfixes are quite easy to couple with tests. Writing the test first actually makes a lot of sense in case of bugfixing.

I think we could rename the `samples` directory to `tests` and put whatever we want to it. Some tests need multiple subdirs/packages (e.g.: https://github.com/golang/mock/issues/85) so putting all that mess into a tests subdir would make sense.

Next time I have some free time I might put together something and open an PR (unless someone implements it earlier).
