### ISSUE TITLE
No code generation mock library

### ISSUE THREAD

**Issue by grovecai** [golang/mock#87]
Is it any possible to implement no code generation mock library? Just like PowerMock in Java.

**Comment by balshetzer** [comment]
I can't think of a way. Go doesn't have any hooks for generating types at run time like Java. If you think of a way then please let us know..

**Comment by balshetzer** [comment]
You could do something sneaky with plugins. It would still require code generation and compilation but it could be done at run time and then loaded by the test. Still, not sure it's worth it.
