### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by akshayjshah** [golang/mock#92]
Hi @balshetzer - thanks for maintaining a great mocking package. We use it extensively internally and appreciate all your hard work!

The recently-committed #89 is backward-incompatible, and breaks a large number of our mocks (across many packages and repositories). It's certainly your prerogative to make backward-breaking changes like this, but it's hard on consumers of this package - particularly because there aren't any [semver-tagged releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases).

Would you consider tagging a 1.0.0 release? There's nothing stopping you from making backward-breaking changes afterwards and tagging a 2.0, but this way consumers can more easily control when they pull in breaking changes.  It'll also make this package work better with tools like `glide` and `dep`.

**Comment by balshetzer** [comment]
Sorry about that. I'll restore backwards compatibility with #93.

I'm curious. Did #89 break your builds because your code calls RecordCall directly or because the mocks are not regenerated as part of your build/test process?

And yes, I'll look into creating these tags so that backwards incompatible changes don't sneak up on consumers in the future.

**Comment by balshetzer** [comment]
I've tagged the current state as v1.0.0. I'll follow the semver rules for version numbering.

**Comment by akshayjshah** [comment]
Our builds broke because the mocks aren't regenerated as part of builds and tests. There's a (possibly) good reason for that, though: like most multi-repository, OSS-style organizations, we check in nearly all generated code.

This makes life much simpler for the consumer of generated packages - it's just code like any other, and only the *author* needs to know that it's generated.

In the case of gomock, though, the generator of the code and the consumer need to agree on a version. Semver makes that much easier.

**Comment by balshetzer** [comment]
@akshayjshah Thanks for the explanation. I'll keep this in mind.
