### ISSUE TITLE
_mr.mock.ctrl.RecordCallWithMethodType undefined (type *gomock.Controller has no field or method RecordCallWithMethodType)

### ISSUE THREAD

**Issue by fzerorubigd** [golang/mock#94]
After last day commits (Jul 22, 2017) we get this on mock generated file. reverting to dbe9dea30dbc5b4b6d54c9ecf9a3b8f9b8e6556c and everything is fine.

I can provide more information if you need, currently searching.

**Comment by balshetzer** [comment]
It sounds like you've updated mockgen but not the gomock package. Is that possible?

**Comment by fzerorubigd** [comment]
Yes. thank you. the vendored version was not updated.
