### ISSUE TITLE
Unknown parameters mock call

### ISSUE THREAD

**Issue by Soulou** [golang/mock#96]
Hi there,

Is there a way to expect a call without giving precisely the expected parameters and get them afterwards ?

Is pseudo code I'd like to do something like this

```
c := m.EXPECT(/* any */).Method()
MyTestedFunc()
s := C.Args[0].(string)
if strings.Contain(s, "test") { 
  // ...
```

Thanks a lot

**Comment by balshetzer** [comment]
Given a method:

`func (receiver) Method(string)
`

You can do:
```
m.EXPECT().Method(gomock.Any()).Call(func (s string) { 
  if strings.Contain(s, "test") { 
    // ...
  }
})
```

There are some other options depending on what you're trying to achieve but this seems easiest.

**Comment by Soulou** [comment]
Thanks a lot :-)
